let verbs = [{
     inf: "arise",
     tr_inf: "[əˈraɪz]",
     pret: "arose",
     tr_pret: "[əˈrəɪz]",
     perf: "arisen",
     tr_perf: "[əˈrɪzn]",
     inf_s:"If the need arises, we can rent another car.",
     pret_s:"A storm arose during the night.",
     perf_s: "A serious problem has arisen.",
     trans: "nastať, vynoriť sa, objaviť sa",
     inf_v: "Ak treba, môžeme prenajať ďalšie auto.",
     pret_v: "Počas noci vznikla búrka.",
     perf_v: "Objavil sa vážny problém."
},
{
     inf: "be",
     tr_inf: "[bi:]",
     pret: "was/were",
     tr_pret: "[woz, wə:]",
     perf: "been",
     tr_perf: "[bi:n]",
     inf_s:"Be carful.",
     pret_s:"He was an excellent footbal player.",
     perf_s: "Have you ever been to Canada?",
     trans: "byť",
     inf_v: "Buď opatrný.",
     pret_v: "On bol vynikajúcim futbalovým hráčom.",
     perf_v: "Bol si už nikedy v Kanade?"
},
{
     inf: "bear",
     tr_inf: "[beə]",
     pret: "bore",
     tr_pret: "[bo:]",
     perf: "born",
     tr_perf: "[bo:n]",
     inf_s:"Alice bears a lot of responsibility for this.",
     pret_s:"The child bore the pain bravely.",
     perf_s: "Peter was born in April.",
     trans: "niesť, znášať, (po)rodiť",
     inf_v: "Alica za to nesie veľa zodpovednosti.",
     pret_v: "Dieťa tu bolesť znášalo statočne.",
     perf_v: "Peter sa narodil v apríli."
},
{
     inf: "beat",
     tr_inf: "[bi:t]",
     pret: "beat",
     tr_pret: "[bi:t]",
     perf: "beaten",
     tr_perf: "[bi:tn]",
     inf_s:"I often beat my friends at chess.",
     pret_s:"The rain beat against the window.",
     perf_s: "Peter has beaten the speed record three times.",
     trans: "biť, tĺcť, poraziť",
     inf_v: "Často porážam svojich priateľov v šachu.",
     pret_v: "Dažď bil do okien.",
     perf_v: "Peter prekonal rýchlostný rekord trikrát."
},
{
     inf: "become",
     tr_inf: "[biˈkam]",
     pret: "became",
     tr_pret: "[biˈkeim]",
     perf: "become",
     tr_pert: "[biˈkam]",
     inf_s:"I often become sad when I watch thes film.",
     pret_s:"They became good friends.",
     perf_s: "Tony has just become a father.",
     trans: "stať sa",
     inf_v: "Často zosmutniem, keď pozerám tento film.",
     pret_v: "Stali sa dobrými priateľmi.",
     perf_v: "Tony sa práve stal otcom."
},
{
     inf: "begin",
     tr_inf: "[biˈgin]",
     pret: "began",
     tr_pret: "[biˈgæn]",
     perf: "begun",
     tr_perf: "[biˈgan]",
     inf_s:"When do you begin work?",
     pret_s:"The little boy began to cry.",
     perf_s: "John hasnˈt begun yet.",
     trans: "začať, začínať",
     inf_v: "Kedy začínaš pracovať?",
     pret_v: "Ten malý chlapec začal plakať.",
     perf_v: "Ján ešte nezačal."
},
{
     inf: "bend",
     tr_inf: "[bend]",
     pret: "bent",
     tr_pret: "[bent]",
     perf: "bent",
     tr_perf: "[bent]",
     inf_s:"The road bends to the right.",
     pret_s:"He bent down to pick up her gloves.",
     perf_s: "She has bent her ski pole by accident.",
     trans: "ohnuť sa, zohnúť sa, prikrčiť",
     inf_v: "Cesta sa ohýba doprava.",
     pret_v: "Sklonil sa a zhvihol jej rukavice.",
     perf_v: "Omylom si ohla lyžiarsku palicu."
},
{
     inf: "bet",
     tr_inf: "[bet]",
     pret: "bet",
     tr_pret: "[bet]",
     perf: "bet",
     tr_perf: "[bet]",
     inf_s:"I bet (that) he won't come.",
     pret_s:"She bet on a horse which came in second.",
     perf_s: "John has just bet ten dollars that he can beat me.",
     trans: "staviť sa",
     inf_v: "Stavim sa, že on nepríde.",
     pret_v: "Stavila na koňa, ktorý prišiel druhý.",
     perf_v: "Ján vsadil desať dolárov, že ma porazí."
},
{
     inf: "bind",
     tr_inf: "[baind]",
     pret: "bound",
     tr_pret: "[baund]",
     perf: "bound",
     tr_perf: "[baund]",
     inf_s:"This memory binds us together.",
     pret_s:"They bound her hands and feet and left.",
     perf_s: "The book is bound in a hard cover.",
     trans: "viazať, spájať",
     inf_v: "Táto spomienka nás spája.",
     pret_v: "Zviazali jej ruky a nohy odišli.",
     perf_v: "Kniha je viazaná v pevnom obale."
},
{
     inf: "bite",
     tr_inf: "[bait]",
     pret: "bit",
     tr_pret: "[bit]",
     perf: "bitten",
     tr_perf: "[bitn]",
     inf_s:"Does your dog bite?",
     pret_s:"The neighbour's dog bit him.",
     perf_s: "I have bitten into my steak.",
     trans: "hrýzť",
     inf_v: "Tvoj pes hryzie?",
     pret_v: "Susedov pes ho pohrýzol.",
     perf_v: "Zahryzol som do rezňa."
},
{
     inf: "bleed",
     tr_inf: "[bli:d]",
     pret: "bled",
     tr_pret: "[bled]",
     perf: "bled",
     tr_perf: "[bled]",
     inf_s:"Your nose is bleeding.",
     pret_s:"She slowly bled to death.",
     perf_s: "I have bled like this before.",
     trans: "krvácať",
     inf_v: "Tvoj nos krváca.",
     pret_v: "Pomaly vykrvácala.",
     perf_v: "Už som predtým tákto krvácal."
},
{
     inf: "blow",
     tr_inf: "[bləu]",
     pret: "blew",
     tr_pret: "[blu:]",
     perf: "blown",
     tr_perf: "[bləun]",
     inf_s:"The wind usually blows from the west.",
     pret_s:"He blew on his tea to cool it.",
     perf_s: "The wind has blown his papers away.",
     trans: "fúkať",
     inf_v: "Vietor zvyčajne fúka od západu.",
     pret_v: "Fukol do čaju, aby ho ochladil.",
     perf_v: "Vietor mu odfúkol papiere."
},
{
     inf: "break",
     tr_inf: "[breik]",
     pret: "broke",
     tr_pret: "[brəuk]",
     perf: "broken",
     tr_perf: "[brəukən]",
     inf_s:"Some glass breaks easily.",
     pret_s:"She broke her leg two weeks ago.",
     perf_s: "He has broken a window.",
     trans: "zlomiť, rozbiť",
     inf_v: "Niektoré sklo sa ľahko rozbíja.",
     pret_v: "Pred dvoma týždňami si zlomila nohu.",
     perf_v: "(Práve) rozbil okno."
},
{
     inf: "breed",
     tr_inf: "[bri:d]",
     pret: "bred",
     tr_pret: "[bred]",
     perf: "bred",
     tr_perf: "[bred]",
     inf_s:"Our neighbours breed cattle and sheep.",
     pret_s:"Success bred a certain arrogance in his case.",
     perf_s: "Toads have bred successfully this yaer.",
     trans: "chovať, pestovať",
     inf_v: "Naši susedia chovajú hovädzí dobytok a ovce.",
     pret_v: "Úspech priniesol v jeho prípade určitú aroganciu.",
     perf_v: "Ropuchy sa tohto roku úspešne rozmnožili."
},
{
     inf: "bring",
     tr_inf: "[briŋ]",
     pret: "brought",
     tr_pret: "[bro:t]",
     perf: "brought",
     tr_perf: "[bro:t]",
     inf_s:"My wife often bring work home.",
     pret_s:"He brought me fresh fruits.",
     perf_s: "What have you brought today?",
     trans: "priniesť",
     inf_v: "Moja žena často nosí prácu domov.",
     pret_v: "On mi priniesol čerstvé ovocie.",
     perf_v: "Čo si dnes priniesol?."
},
{
     inf: "broadcast",
     tr_inf: "['bro:dka:st]",
     pret: "broadcast",
     tr_pret: "['bro:dka:st]",
     perf: "broadcast",
     tr_perf: "['bro:dka:st]",
     inf_s:"They broadcast the news every day.",
     pret_s:"Radio One broadcast the tennis match last night.",
     perf_s: "The interview was broadcast live.",
     trans: "vysielať",
     inf_v: "Správy sa vysielajú každý deň.",
     pret_v: "Rádio One vysielalo tenisový zápas včera v noci.",
     perf_v: "Rozhovor bol vysielaný naživo."
},

]

let app = new Vue({
  el: '.page',
  data: {
    message: 'Hello Vue!',
    verbs: verbs
  }
})
