let cats = {
cat0:[{
    img: "28.png",
    inf: "do",
    tr_inf: "[du:]",
    pret: "did",
    tr_pret: "[did]",
    perf: "done",
    tr_perf: "[dan]",
    inf_s:"What do you do for living?",
    pret_s:"I did some work yesterday.",
    perf_s: "I have done what I promised.",
    trans: "robiť",
    inf_v: "Aké je tvoje povolanie?",
    pret_v: "Včera som urobil nejakú robotu.",
    perf_v: "Spavil som, čo som sľubil."
}],
cat1:[
    {
    img: "5.png",
    inf: "become",
    tr_inf: "[biˈkam]",
    pret: "became",
    tr_pret: "[biˈkeim]",
    perf: "become",
    tr_perf: "[biˈkam]",
    inf_s:"I often become sad when I watch thes film.",
    pret_s:"They became good friends.",
    perf_s: "Tony has just become a father.",
    trans: "stať sa",
    inf_v: "Často zosmutniem, keď pozerám tento film.",
    pret_v: "Stali sa dobrými priateľmi.",
    perf_v: "Tony sa práve stal otcom."
},
{
    img: "22.png",
    inf: "come",
    tr_inf: "[kam]",
    pret: "came",
    tr_pret: "[keim]",
    perf: "come",
    tr_perf: "[kam]",
    inf_s:"I always come to class prepared.",
    pret_s:"Winter came early that year.",
    perf_s: "He hasn't come to the party yet.",
    trans: "prísť",
    inf_v: "Vždy idem na hodinu pripravený.",
    pret_v: "Zima prišla tento rok skoro.",
    perf_v: "Ešte neprišiel na večierok."
},
{
    img: "79.png",
    inf: "run",
    tr_inf: "[ran]",
    pret: "ran",
    tr_pret: "[ræn]",
    perf: "run",
    tr_perf: "[ran]",
    inf_s: "He runs along the beach every Monday.",
    pret_s: "Janet ran five miles yesterday.",
    perf_s: "I have run a long way today.",
    trans: "bežať",
    inf_v: "Každý pondelok behá po pláži",
    pret_v: "Žaneta včera ubehla 5 míľ.",
    perf_v: "Dnes som bežal ďaleko."
}
],
cat2:[
    {
    img: "8.png",
    inf: "bet",
    tr_inf: "[bet]",
    pret: "bet",
    tr_pret: "[bet]",
    perf: "bet",
    tr_perf: "[bet]",
    inf_s:"I bet (that) he won't come.",
    pret_s:"She bet on a horse which came in second.",
    perf_s: "John has just bet ten dollars that he can beat me.",
    trans: "staviť sa",
    inf_v: "Stavim sa, že on nepríde.",
    pret_v: "Stavila na koňa, ktorý prišiel druhý.",
    perf_v: "Ján vsadil desať dolárov, že ma porazí."
},
{
    img: "16.png",
    inf: "broadcast",
    tr_inf: "['bro:dka:st]",
    pret: "broadcast",
    tr_pret: "['bro:dka:st]",
    perf: "broadcast",
    tr_perf: "['bro:dka:st]",
    inf_s:"They broadcast the news every day.",
    pret_s:"Radio One broadcast the tennis match last night.",
    perf_s: "The interview was broadcast live.",
    trans: "vysielať",
    inf_v: "Správy sa vysielajú každý deň.",
    pret_v: "Rádio One vysielalo tenisový zápas včera v noci.",
    perf_v: "Rozhovor bol vysielaný naživo."
},
{
    img: "19.png",
    inf: "burst",
    tr_inf: "[bə:st]",
    pret: "burst",
    tr_pret: "[bə:st]",
    perf: "burst",
    tr_perf: "[bə:st]",
    inf_s:"Sometimes she bursts her brother's balloon on purpose.",
    pret_s:"She burst into the room without knocking.",
    perf_s: "She's burst into tears.",
    trans: "prasknúť, puknúť, ",
    inf_v: "Ona niekedy naschval praskne balón svojho brata.",
    pret_v: "Bez klopania vpadla do izby.",
    perf_v: "Vpadla do sĺz."
},
{
    img: "23.png",
    inf: "cost",
    tr_inf: "[kost]",
    pret: "cost",
    tr_pret: "[kost]",
    perf: "cost",
    tr_perf: "[kost]",
    inf_s:"How much does this book cost?",
    pret_s:"My first bike cost 200$.",
    perf_s: "My mistake has already cost me a lot of money.",
    trans: "stáť (máť cenu)",
    inf_v: "Koľko stojí táto kniha?",
    pret_v: "Môj prvý bicykel stál 200$.",
    perf_v: "Môj omyl ma už stál veľa peňazí."
},
{
    img: "25.png",
    inf: "cut",
    tr_inf: "[kat]",
    pret: "cut",
    tr_pret: "[kat]",
    perf: "cut",
    tr_perf: "[kat]",
    inf_s:"This knife cuts well.",
    pret_s:"My daughter cut her finger yesterday.",
    perf_s: "She has just cut herself.",
    trans: "rezať, krájať",
    inf_v: "Tento nôž dobre krája.",
    pret_v: "Moja dcéra si včera porezala prst.",
    perf_v: "Práve sa porezala."
},
{
    img: "43.png",
    inf: "forecast",
    tr_inf: "['fo:ka:st]",
    pret: "forecast",
    tr_pret: "['fo:ka:st]",
    perf: "forecast",
    tr_perf: "['fo:ka:st]",
    inf_s: "They forecast a fall in profits.",
    pret_s: "She forecast that the unemployment rate would fail slightly.",
    perf_s: "Snow is forecast tonight.",
    trans: "predpovedať",
    inf_v: "Predpovedajú pokles zisku.",
    pret_v: "Predpokladala, že miera nezamestnanosti mierne klesne.",
    perf_v: "Dnes večer je predpovedaný sneh."
},
{
    img: "53.png",
    inf: "hit",
    tr_inf: "[hit]",
    pret: "hit",
    tr_pret: "[hit]",
    perf: "hit",
    tr_perf: "[hit]",
    inf_s: "My father never hits me.",
    pret_s: "She hit her thumb with the hammer yesterday.",
    perf_s: "Why has he hit you?",
    trans: "udrieť, trafiť",
    inf_v: "Môj otec ma nikdy nebije.",
    pret_v: "Včera sa trafila kladivom do palca.",
    perf_v: "Prečo ťa udrel?"
},
{   
    img: "55.png",
    inf: "hurt",
    tr_inf: "[hə:t]",
    pret: "hurt",
    tr_pret: "[hə:t]",
    perf: "hurt",
    tr_perf: "[hə:t]",
    inf_s: "Tell me where it hurts.",
    pret_s: "Emma hurt her back when she fell off her horse.",
    perf_s: "How have you hurt yourself?",
    trans: "zraniť, bolieť",
    inf_v: "Povedz mi, kde to bolí.",
    pret_v: "Emma si zranila chrbát, keď spadla z koňa.",
    perf_v: "Ako si sa zranil?"
},
{
    img: "65.png",
    inf: "let",
    tr_inf: "[let]",
    pret: "let",
    tr_pret: "[let]",
    perf: "let",
    tr_perf: "[let]",
    inf_s: "This ticket lets you travel anywhere in the city.",
    pret_s: "I let him hold my hand.",
    perf_s: "He live with me, I have let him stay.",
    trans: "nechať, dovoliť",
    inf_v: "Tento lístok ti umožnuje cestovať kamkoľvek v meste.",
    pret_v: "Dovolila som mu držať ma za ruku.",
    perf_v: "Býva som mnou, dovolila som mu ostať."
},
{
    img: "74.png",
    inf: "put",
    tr_inf: "[put]",
    pret: "put",
    tr_pret: "[put]",
    perf: "put",
    tr_perf: "[put]",
    inf_s: "Where do you put your clothes?",
    pret_s: "Charlotte put the bag on the table.",
    perf_s: "Where have you put the keys.",
    trans: "položiť, dať",
    inf_v: "Kam dávaš šaty?",
    pret_v: "Šarlota položila tašku na stôl.",
    perf_v: "Kam si dal kľuče?"
},
{
    img: "75.png",
    inf: "read",
    tr_inf: "[ri:d]",
    pret: "read",
    tr_pret: "[red]",
    perf: "read",
    tr_perf: "[red]",
    inf_s: "I read every night.",
    pret_s: "I read this book last year.",
    perf_s: "i have read all your books already.",
    trans: "čítať",
    inf_v: "Čítam si každú noc.",
    pret_v: "Túto knihu som čítal minulý rok.",
    perf_v: "Už som prečítal všetky tvoje knihy."
},
{
    img: "86.png",
    inf: "set",
    tr_inf: "[set]",
    pret: "set",
    tr_pret: "[set]",
    perf: "set",
    tr_perf: "[set]",
    inf_s: "I set high standards for myself.",
    pret_s: "She set her alarm clock for 6.00 a.m.",
    perf_s: "She's set the cup of tea down and left.",
    trans: "nastaviť, položiť",
    inf_v: "Mám na seba vysoké požiadavky.",
    pret_v: "Nastavila (si) budík na 6.00 ráno.",
    perf_v: "Položila šálku s čajom a odišla."
},
{
    img: "93.png",
    inf: "shut",
    tr_inf: "[šat]",
    pret: "shut",
    tr_pret: "[šat]",
    perf: "shut",
    tr_perf: "[šat]",
    inf_s: "I shut the door quietly.",
    pret_s: "Mary shut her book and went to sleep.",
    perf_s: "I have already shut the window.",
    trans: "zatvoriť",
    inf_v: "Zatváram dvere potichu.",
    pret_v: "Mária zatvorila knihu a išla spať.",
    perf_v: "Už som to okno zavrela."
},
{
    img: "104.png",
    inf: "split",
    tr_inf: "[split]",
    pret: "split",
    tr_pret: "[split]",
    perf: "split",
    tr_perf: "[split]",
    inf_s: "I always split the money equally.",
    pret_s: "The teacher split the class into groups.",
    perf_s: "Susan and I have already split up.",
    trans: "rozdeliť (sa)",
    inf_v: "Vždy delím peniaze rovnakým dielom.",
    pret_v: "Učiteľ rozdelil triedu na skupiny.",
    perf_v: "Zuzana a ja sme sa už rozišli."
},
{
    img: "106.png",
    inf: "spread",
    tr_inf: "[spred]",
    pret: "spread",
    tr_pret: "[spred]",
    perf: "spread",
    tr_perf: "[spred]",
    inf_s: "The disease spreads easily.",
    pret_s: "The eagle spread its wings and flew away.",
    perf_s: "The map was spread on the carpet.",
    trans: "rozširovať, roztiahnuť, rozprestrieť",
    inf_v: "Tá choroba sa šíri ľahko.",
    pret_v: "Orol roztiahol krídla a odletel.",
    perf_v: "Na koberci bola rozprestretá mapa."
}],
cat3:[
{
    img: "3.png",
    inf: "bear",
    tr_inf: "[beə]",
    pret: "bore",
    tr_pret: "[bo:]",
    perf: "born",
    tr_perf: "[bo:n]",
    inf_s:"Alice bears a lot of responsibility for this.",
    pret_s:"The child bore the pain bravely.",
    perf_s: "Peter was born in April.",
    trans: "niesť, znášať, (po)rodiť",
    inf_v: "Alica za to nesie veľa zodpovednosti.",
    pret_v: "Dieťa tu bolesť znášalo statočne.",
    perf_v: "Peter sa narodil v apríli."
},
{
    img:"6.png",
    inf: "begin",
    tr_inf: "[biˈgin]",
    pret: "began",
    tr_pret: "[biˈgæn]",
    perf: "begun",
    tr_perf: "[biˈgan]",
    inf_s:"When do you begin work?",
    pret_s:"The little boy began to cry.",
    perf_s: "John hasnˈt begun yet.",
    trans: "začať, začínať",
    inf_v: "Kedy začínaš pracovať?",
    pret_v: "Ten malý chlapec začal plakať.",
    perf_v: "Ján ešte nezačal."
},
{
    img:"10.png",
    inf: "bite",
    tr_inf: "[bait]",
    pret: "bit",
    tr_pret: "[bit]",
    perf: "bitten",
    tr_perf: "[bitn]",
    inf_s:"Does your dog bite?",
    pret_s:"The neighbour's dog bit him.",
    perf_s: "I have bitten into my steak.",
    trans: "hrýzť",
    inf_v: "Tvoj pes hryzie?",
    pret_v: "Susedov pes ho pohrýzol.",
    perf_v: "Zahryzol som do rezňa."
},
{
    img:"12.png",
    inf: "blow",
    tr_inf: "[bləu]",
    pret: "blew",
    tr_pret: "[blu:]",
    perf: "blown",
    tr_perf: "[bləun]",
    inf_s:"The wind usually blows from the west.",
    pret_s:"He blew on his tea to cool it.",
    perf_s: "The wind has blown his papers away.",
    trans: "fúkať",
    inf_v: "Vietor zvyčajne fúka od západu.",
    pret_v: "Fukol do čaju, aby ho ochladil.",
    perf_v: "Vietor mu odfúkol papiere."
},
{
    img:"13.png",
    inf: "break",
    tr_inf: "[breik]",
    pret: "broke",
    tr_pret: "[brəuk]",
    perf: "broken",
    tr_perf: "[brəukən]",
    inf_s:"Some glass breaks easily.",
    pret_s:"She broke her leg two weeks ago.",
    perf_s: "He has broken a window.",
    trans: "zlomiť, rozbiť",
    inf_v: "Niektoré sklo sa ľahko rozbíja.",
    pret_v: "Pred dvoma týždňami si zlomila nohu.",
    perf_v: "(Práve) rozbil okno."
},
{
    img:"56.png",
    inf: "choose",
    tr_inf: "[ču:z]",
    pret: "chose",
    tr_pret: "[čəuz]",
    perf: "chosen",
    tr_perf: "[čəuzən]",
    inf_s: "How do you choose your friends?",
    pret_s: "I chose a red dress.",
    perf_s: "We've chosen a present for Katie today.",
    trans: "zvoliť, vybrať (si)",
    inf_v: "Ako si vyberáš priateľov",
    pret_v: "Zvolila som červené šaty.",
    perf_v: "Dnes sme vybrali darček pre Katku."
},
{
    img:"31.png",
    inf: "drink",
    tr_inf: "[driŋk]",
    pret: "drank",
    tr_pret: "[dræŋk]",
    perf: "drunk",
    tr_perf: "[draŋk]",
    inf_s: "Do you drink beer?",
    pret_s: "Jack drank a glass of apple juice.",
    perf_s: "He has drunk all day.",
    trans: "piť",
    inf_v: "Piješ pivo?",
    pret_v: "Jack vypil pohár jablkového džúsu.",
    perf_v: "Pije celý deň."
},
{
    img:"39.png",
    inf: "fly",
    tr_inf: "[flai]",
    pret: "flew",
    tr_pret: "[flu:]",
    perf: "flown",
    tr_perf: "[floun]",
    inf_s: "I usually fly by Aeroflot.",
    pret_s: "George flew to Maimi last week.",
    perf_s: "Emily flown many times in her life.",
    trans: "letieť",
    inf_v: "Zvyčajne lietam s Aeroflotom.",
    pret_v: "Juraj odletel minulý týždeň na Miami.",
    perf_v: "Emilia už letela veľakrát v živote."
},
{
    img:"41.png",
    inf: "forget",
    tr_inf: "[fə'get]",
    pret: "forgot",
    tr_pret: "[fə'got]",
    perf: "forgotten",
    tr_perf: "[fə'gotn]",
    inf_s: "He often forget to do his homework.",
    pret_s: "I forgot my umbrella at home.",
    perf_s: "Have you ever forgotten an appointment?",
    trans: "zabudnúť",
    inf_v: "Často si zabudne spraviť domácu úlohu.",
    pret_v: "Zabudol som si doma dáždnik.",
    perf_v: "Zabudol si už niekedy na schôdzku?"
},
{
    img:"44.png",
    inf: "freeze",
    tr_inf: "[fri:z]",
    pret: "froze",
    tr_pret: "[frəuz]",
    perf: "frozen",
    tr_perf: "['frəuz(ə)n]",
    inf_s: "Water freezes at zero degrees Celsius.",
    pret_s: "A climber froze to death on the mountain.",
    perf_s: "Her bank account has been frozen.",
    trans: "(za)mrznúť",
    inf_v: "Voda zamrzne pri nula stupňoch Celsia.",
    pret_v: "Horolezec zamrzol na vrchole hory.",
    perf_v: "Jej bankový účet bol zmrazený."
},
{
    img:"52.png",
    inf: "hide",
    tr_inf: "[haid]",
    pret: "hid",
    tr_pret: "[hid]",
    perf: "hidden",
    tr_perf: "[hidn]",
    inf_s: "Jack hides his money under his bed.",
    pret_s: "She hid the letter in the bookcase.",
    perf_s: "What have you just hidden?",
    trans: "skryť",
    inf_v: "Jack skrýva svoje peniaze pod posteľ.",
    pret_v: "Skryla ten list v knižnici.",
    perf_v: "Čo si práve ukryl?"
},
{
    img:"66.png",
    inf: "lie",
    tr_inf: "[lai]",
    pret: "lay",
    tr_pret: "[lei]",
    perf: "lain",
    tr_perf: "[lein]",
    inf_s: "The river lies 30 km to the south.",
    pret_s: "A pen lay on the desk.",
    perf_s: "How long has the dog lain here?",
    trans: "ležať",
    inf_v: "Rieka leží 30 km na juh.",
    pret_v: "Na stole ležalo pero.",
    perf_v: "Ako dlko tu ten pes leží?"
},
{
    img:"77.png",
    inf: "ring",
    tr_inf: "[riŋ]",
    pret: "rang",
    tr_pret: "[ræŋ]",
    perf: "rung",
    tr_perf: "[raŋ]",
    inf_s: "The church bell rings every Sunday.",
    pret_s: "I rang the bell but nobody answered the door.",
    perf_s: "I have just rung Thomas.",
    trans: "zvoniť",
    inf_v: "Kostolný zvon zvoní každú nedeľu.",
    pret_v: "Zazvonil som, ale nikto neotvoril.",
    perf_v: "Práve som zavolal Tomášovi."
},
{
    img:"92.png",
    inf: "shrink",
    tr_inf: "[šriŋk]",
    pret: "shrank",
    tr_pret: "[šræŋk]",
    perf: "shrunk",
    tr_perf: "[šraŋk]",
    inf_s: "Hot water shrinks woollen clothes.",
    pret_s: "She shrank away from his touch.",
    perf_s: "The number of students has shrunk from 80 to 60.",
    trans: "zmenšiť sa, zmrštiť",
    inf_v: "Horúca voda zmršťuje vlnené oblečenie.",
    pret_v: "Odtiahla sa od jeho dotyku.",
    perf_v: "Počet študentov sa zmenšil zo 80 na 60."
},
{
    img:"94.png",
    inf: "sing",
    tr_inf: "[siŋ]",
    pret: "sang",
    tr_pret: "[sæn]",
    perf: "sung",
    tr_perf: "[saŋ]",
    inf_s: "William always sings in the bath.",
    pret_s: "She sang a funny song about fish.",
    perf_s: "My daughter has never sung in public.",
    trans: "spievať",
    inf_v: "Viliam si vždy spieva vo vani.",
    pret_v: "Zaspievala žartovnú pieseň o rybe.",
    perf_v: "Moja sestra nikdy nespievala na verejnosti."
},
{
    img:"95.png",
    inf: "sink",
    tr_inf: "[siŋk]",
    pret: "sank",
    tr_pret: "[sæŋk]",
    perf: "sunk",
    tr_perf: "[saŋk]",
    inf_s: "If you throw a stone into water, it sinks.",
    pret_s: "The Titanic sank in 1912.",
    perf_s: "Last year many countries have sunk into crisis.",
    trans: "potopiť sa, klesať",
    inf_v: "Ak hodíte kameň do vody, klesne.",
    pret_v: "Titanic sa potopil v roku 1912.",
    perf_v: "Minulého roku sa mnohé krajiny dostali do krízy."
},
{
    img:"100.png",
    inf: "speak",
    tr_inf: "[spi:k]",
    pret: "spoke",
    tr_pret: "[spəuk]",
    perf: "spoken",
    tr_perf: "[spəukən]",
    inf_s: "He speaks English with an American accent.",
    pret_s: "We spoke on the phone yesterday.",
    perf_s: "I haven't spoken to him for a few weeks.",
    trans: "hovoriť",
    inf_v: "Hovorí po anglický s americkým prízvukom.",
    pret_v: "Včera sme spolu hovorili telefonicky.",
    perf_v: "Nehovoril som s nim niekoľko týždňov."
},
{
    img:"109.png",
    inf: "steal",
    tr_inf: "[sti:l]",
    pret: "stole",
    tr_pret: "[stəul]",
    perf: "stolen",
    tr_perf: "[stəulən]",
    inf_s: "They steal food just to stay alive.",
    pret_s: "Someone stole my luggage last summer.",
    perf_s: "The girl has never stolen anything.",
    trans: "(u)radnúť",
    inf_v: "Kadnú jedlo, aby ostali nažive.",
    pret_v: "Minulé leto mi niekto ukradol batožinu.",
    perf_v: "To dievča nikdy nič neukradlo."
},
{
    img:"112.png",
    inf: "stink",
    tr_inf: "[stiŋk]",
    pret: "stank",
    tr_pret: "[stæŋk]",
    perf: "stunk",
    tr_perf: "[staŋk]",
    inf_s: "Your shoes stink!",
    pret_s: "his breath stank of alcohol.",
    perf_s: "The garbage has stunk here for the last two days.",
    trans: "páchnuť, smrdieť",
    inf_v: "Tvoje topánky smrdia!",
    pret_v: "Jeho dych páchol alkoholom.",
    perf_v: "Tie odpadky tu smrdia už dva dni."
},
{
    img:"114.png",
    inf: "swear",
    tr_inf: "[sweə]",
    pret: "swore",
    tr_pret: "[swo:]",
    perf: "sworn",
    tr_perf: "[swo:n]",
    inf_s: "I swear (that) I'll never leave you.",
    pret_s: "He shouted and swore at her aggressively.",
    perf_s: "You have sworn to tell the truth.",
    trans: "prisahať, nadávať",
    inf_v: "Prisahám (to), že ťa nikdy neopustím.",
    pret_v: "Agresivne na ňu kričal a nadával.",
    perf_v: "Si prísahal, že budeš hovoriť pravdu."
},
{
    img:"116.png",
    inf: "swell",
    tr_inf: "[swel]",
    pret: "swelled",
    tr_pret: "[sweld]",
    perf: "swollen",
    tr_perf: "[swəulən]",
    inf_s: "My ankles swell if I stand too long.",
    pret_s: "Her feet sweelled up after the long walk.",
    perf_s: "The river was swollen with melted snow.",
    trans: "opuchať, otiekať",
    inf_v: "Keď dlho stojim otekajú mi kotníky.",
    pret_v: "Po dlhej prechádzke jej opuchli chodidla.",
    perf_v: "Rieku rozvodnil roztavený sneh."
},
{
    img:"117.png",
    inf: "swim",
    tr_inf: "[swim]",
    pret: "swam",
    tr_pret: "[swæm]",
    perf: "swum",
    tr_perf: "[swam]",
    inf_s: "Jack swims slowly.",
    pret_s: "I swam one mile yesterday morning.",
    perf_s: "My daughter hasn't swum in the sea yet.",
    trans: "plávať",
    inf_v: "Jack pláva pomaly.",
    pret_v: "Včera ráno som zaplával jednu míľu.",
    perf_v: "Moja dcéra ešte neplávala v mori."
},
{
    img:"121.png",
    inf: "tear",
    tr_inf: "[teə]",
    pret: "tore",
    tr_pret: "[to:]",
    perf: "torn",
    tr_perf: "[to:n]",
    inf_s: "After reading a letter, Paul usually tears it to pieces.",
    pret_s: "I tore my jeans on the fence.",
    perf_s: "Someone has torn a page out of the book.",
    trans: "trhať sa",
    inf_v: "Po prečítaní listu ho Paul zvyčajne roztrhá.",
    pret_v: "Roztrhol som si rifle o plot.",
    perf_v: "Niekto vytrhol stránku z knihy."
},
{
    img:"126.png",
    inf: "wake",
    tr_inf: "[weik]",
    pret: "woke",
    tr_pret: "[wəuk]",
    perf: "woken",
    tr_perf: "[wəuken]",
    inf_s: "My mother usually wakes me at seven.",
    pret_s: "He woke me early.",
    perf_s: "Have you finally woken up?",
    trans: "zobudiť sa",
    inf_v: "Moja matka ma zvyčajne budí o siedmej.",
    pret_v: "Zobudil ma skoro.",
    perf_v: "Už si sa konečne zobudil?"
},
{
    img:"127.png",
    inf: "wear",
    tr_inf: "[weə]",
    pret: "wore",
    tr_pret: "[wo:]",
    perf: "worn",
    tr_perf: "[wo:n]",
    inf_s: "James wears glasses for reading.",
    pret_s: "His brouther wore a yellow shirt.",
    perf_s: "Have you ever worn a school uniform?",
    trans: "nosiť, mať (na sebe)",
    inf_v: "James nosí okuliare na čítanie.",
    pret_v: "Jeho brat nosil žltú košeľu.",
    perf_v: "Už si niekedy mal na sebe školskú uniformu?"
},
],
cat4:[{
    img:"1.png",
    inf: "arise",
    tr_inf: "[əˈraɪz]",
    pret: "arose",
    tr_pret: "[əˈrəɪz]",
    perf: "arisen",
    tr_perf: "[əˈrɪzn]",
    inf_s:"If the need arises, we can rent another car.",
    pret_s:"A storm arose during the night.",
    perf_s: "A serious problem has arisen.",
    trans: "nastať, vynoriť sa, objaviť sa",
    inf_v: "Ak treba, môžeme prenajať ďalšie auto.",
    pret_v: "Počas noci vznikla búrka.",
    perf_v: "Objavil sa vážny problém."
},
{
    img:"4.png",
    inf: "beat",
    tr_inf: "[bi:t]",
    pret: "beat",
    tr_pret: "[bi:t]",
    perf: "beaten",
    tr_perf: "[bi:tn]",
    inf_s:"I often beat my friends at chess.",
    pret_s:"The rain beat against the window.",
    perf_s: "Peter has beaten the speed record three times.",
    trans: "biť, tĺcť, poraziť",
    inf_v: "Často porážam svojich priateľov v šachu.",
    pret_v: "Dažď bil do okien.",
    perf_v: "Peter prekonal rýchlostný rekord trikrát."
},
{
    img:"28.png",
    inf: "do",
    tr_inf: "[du:]",
    pret: "did",
    tr_pret: "[did]",
    perf: "done",
    tr_perf: "[dan]",
    inf_s:"What do you do for living?",
    pret_s:"I did some work yesterday.",
    perf_s: "I have done what I promised.",
    trans: "robiť",
    inf_v: "Aké je tvoje povolanie?",
    pret_v: "Včera som urobil nejakú robotu.",
    perf_v: "Spavil som, čo som sľubil."
},
{
    img: "29.png",
    inf: "draw",
    tr_inf: "[dro:]",
    pret: "drew",
    tr_pret: "[dru:]",
    perf: "drawn",
    tr_perf: "[dro:n]",
    inf_s: "I often draw picture with my sister.",
    pret_s: "Show me which picture you drew.",
    perf_s: "Jane has drawn four portraits today.",
    trans: "kresliť",
    inf_v: "Často kreslím obrazky so svojou sestrou.",
    pret_v: "Ukáž mi, ktorý obrázok si nakreslil.",
    perf_v: "Jana dnes nakreslila štyri portrety."
},
{
    img: "32.png",
    inf: "drive",
    tr_inf: "[draiv]",
    pret: "drove",
    tr_pret: "[drəuv]",
    perf: "driven",
    tr_perf: "[drivn]",
    inf_s: "He drives a blue sposrts car.",
    pret_s: "I drove to work that morning.",
    perf_s: "I have never driven a car before.",
    trans: "ísť, šoferovať",
    inf_v: "Šoféruje modré športové auto.",
    pret_v: "To ráno som šiel do práce autom.",
    perf_v: "Predtým som auto nikdy nešoféroval."
},
{
    img: "33.png",
    inf: "eat",
    tr_inf: "[i:t]",
    pret: "ate",
    tr_pret: "[eit]",
    perf: "eaten",
    tr_perf: "[i:tn]",
    inf_s: "I usually eat a toast for breakfast.",
    pret_s: "We ate at home last night.",
    perf_s: "Oliver has already eaten.",
    trans: "jesť",
    inf_v: "Väčšinou jem na raňajky hrianku.",
    pret_v: "Včera večer sme jedli doma.",
    perf_v: "Oliver už jedol."
},
{
    img: "34.png",
    inf: "fall",
    tr_inf: "[fo:l]",
    pret: "fell",
    tr_pret: "[fel]",
    perf: "fallen",
    tr_perf: "[fo:lən]",
    inf_s: "The apple never falls far from the tree.",
    pret_s: "I fell down the stairs and injured my back.",
    perf_s: "I have just fallen in love.",
    trans: "padať, spadnúť",
    inf_v: "Jablko nikdy nepadá ďaleko od stromu.",
    pret_v: "Spadol som zo schodov a poranil si chrbát.",
    perf_v: "Práve som sa zaľúbil."
},
{
    img: "40.png",
    inf: "forbid",
    tr_inf: "[fə'bid]",
    pret: "forbade",
    tr_pret: "[fə'bæd]",
    perf: "forbidden",
    tr_perf: "[fə'bidn]",
    inf_s: "The law forbids the sale of cigaretts to people under the age of 18.",
    pret_s: "The cliffs forbade any easy turning movement.",
    perf_s: "She was forbidden from seeing him again.",
    trans: "zakázať",
    inf_v: "Zákon zakazuje predaj cigariet osobám mladším ako 18 rokov.",
    pret_v: "Útesy nedovolili ľahké otočenie.",
    perf_v: "Mala zakázané ho znova vidieť."
},
{
    img: "42.png",
    inf: "forgive",
    tr_inf: "[fə'give]",
    pret: "forgave",
    tr_pret: "[fə'geiv]",
    perf: "forgiven",
    tr_perf: "[fə:givn]",
    inf_s: "I always forgive him everything.",
    pret_s: "She forgave him yesterday for loosing the ring.",
    perf_s: "I have already forgiven him.",
    trans: "odpustiť",
    inf_v: "Vždy mu všetko odpustím.",
    pret_v: "Včera mu odpustila, že stratil prsteň.",
    perf_v: "Už som mu odpustila."
},
{
    img: "46.png",
    inf: "give",
    tr_inf: "[giv]",
    pret: "gave",
    tr_pret: "[geiv]",
    perf: "given",
    tr_perf: "[givn]",
    inf_s: "Every year they give us a lot of presents.",
    pret_s: "I gave Harry a book for his birthday.",
    perf_s: "Has he given you enough information?",
    trans: "dať, dávať",
    inf_v: "Každý rok nám dávajú množstvo darčekov.",
    pret_v: "Dala som Harrymu knihu na narodeniny.",
    perf_v: "Dal ti dostatok informácií?"
},
{
    img: "47.png",
    inf: "go",
    tr_inf: "[gəu:]",
    pret: "went",
    tr_pret: "[went]",
    perf: "gone",
    tr_perf: "[gon]",
    inf_s: "My brother usually goes home by bus.",
    pret_s: "I went to the cinema last week.",
    perf_s: "Peter has already gone to the bank.",
    trans: "ísť, jazdiť",
    inf_v: "Môj brat ide zvýčajne domov autobusom.",
    pret_v: "Minulý týždeň som išiel do kina.",
    perf_v: "Peter iž odisiel do banky."
},
{
    img: "48.png",
    inf: "grow",
    tr_inf: "[grəu]",
    pret: "grew",
    tr_pret: "[gru:]",
    perf: "grown",
    tr_perf: "[grəun]",
    inf_s: "Roses grow well in our garden.",
    pret_s: "They grew the best tomatoes last summer.",
    perf_s: "Lisa has grown five centimeters this year.",
    trans: "rásť, pestovať",
    inf_v: "Ruže v našej zahrade pekne rastú.",
    pret_v: "Minulé leto vypestovali najlepšie paradajky.",
    perf_v: "Liza vyrástla tento rok o päť centimetrov."
},
{
    img: "59.png",
    inf: "know",
    tr_inf: "[nəu]",
    pret: "knew",
    tr_pret: "[nju:]",
    perf: "known",
    tr_perf: "[nəun]",
    inf_s: "I don't know who lives there.",
    pret_s: "She knew it was time to leave.",
    perf_s: "They have known each other for years.",
    trans: "vedieť, poznať",
    inf_v: "Neviem, kto tam býva.",
    pret_v: "Vedela, že je čas odísť.",
    perf_v: "Poznajú sa už roky."
},
{
    img: "72.png",
    inf: "overtake",
    tr_inf: "[əuvə'teik]",
    pret: "overtook",
    tr_pret: "[əuvə'tuk]",
    perf: "overtaken",
    tr_perf: "[əuvə'teikən]",
    inf_s: "Drivers usually overtake cyclists.",
    pret_s: "He overtook him by two laps.",
    perf_s: "She was overtaken by sudden panic.",
    trans: "predbehnúť, zasiahnuť",
    inf_v: "Vodiči zvyčajne predbehnú cyklistov",
    pret_v: "Prekonal ho o dve kolá.",
    perf_v: "Zasiahla ju panika."
},
{
    img: "76.png",
    inf: "ride",
    tr_inf: "[raid]",
    pret: "rode",
    tr_pret: "[rəud]",
    perf: "ridden",
    tr_perf: "[ridn]",
    inf_s: "Joseph rides his motocycle to work.",
    pret_s: "Peter rode his bicykle to school last week.",
    perf_s: "Have you ever ridden a horse?",
    trans: "ísť, jazdiť",
    inf_v: "Jozef jazdí do práce na motorke.",
    pret_v: "Peter išiel minulý týždeň do školy na bicykli.",
    perf_v: "Už si niekedy jazdil na koni?"
},
{
    img: "78.png",
    inf: "rise",
    tr_inf: "[raiz]",
    pret: "rose",
    tr_pret: "[rəuz]",
    perf: "risen",
    tr_perf: "[rizn]",
    inf_s: "The sun rises in the east.",
    pret_s: "The balloon rose gently (up) into the air.",
    perf_s: "The cost of living has risen sharply.",
    trans: "vstať, stúpať",
    inf_v: "Slnko vychádza na východe.",
    pret_v: "Balón sa zľahka vzniesol so vzduchu.",
    perf_v: "Životné náklady prudko stúpli."
},
{
    img: "80.png",
    inf: "saw",
    tr_inf: "[so:]",
    pret: "sawed",
    tr_pret: "[so:d]",
    perf: "sawn",
    tr_perf: "[so:n]",
    inf_s: "I saw logs for my fire every morning.",
    pret_s: "I sawed the board in half.",
    perf_s: "Our gardener has sawn a large branch from this tree.",
    trans: "rezať",
    inf_v: "Každé ráno režem drevo do ohňa.",
    pret_v: "Rozrezal som tu dosku na polovicu.",
    perf_v: "Náš zahradník odrezal veľkú vetvu z tohto stromu."
},
{
    img: "82.png",
    inf: "see",
    tr_inf: "[si:]",
    pret: "saw",
    tr_pret: "[so:]",
    perf: "seen",
    tr_perf: "[si:n]",
    inf_s: "I see my grandparents every week.",
    pret_s: "Thomas saw Peter last weekend.",
    perf_s: "Have you seen my glasses anywhere?",
    trans: "vidieť, navštíviť",
    inf_v: "Každý týždeň navštevujem svojich starých rodičov.",
    pret_v: "Tomáš videl Petra minulý víkend.",
    perf_v: "Nevidel si niekde moje okuliare?"
},
{
    img: "88.png",
    inf: "shake",
    tr_inf: "[šiek]",
    pret: "shook",
    tr_pret: "[šuk]",
    perf: "shaken",
    tr_perf: "[šeikən]",
    inf_s: "The windows shake when it's windy.",
    pret_s: "He shook his head in disapproval.",
    perf_s: "She was visibly shaken by the news.",
    trans: "triasť, šokovať",
    inf_v: "Okná sa otriasajú, keď sú vetrom.",
    pret_v: "Zavrel hlavou bez súhlasu.",
    perf_v: "Očividne tou správou bola otrasená."
},
{
    img: "91.png",
    inf: "show",
    tr_inf: "[šəu]",
    pret: "showed",
    tr_pret: "[šəud]",
    perf: "shown",
    tr_perf: "[šəun]",
    inf_s: "This map shows the city centre.",
    pret_s: "He showed me his old pictures.",
    perf_s: "Has John shown you his new flat yet?",
    trans: "ukázať, ukazovať",
    inf_v: "Táto mapa ukazuje centrum mesta.",
    pret_v: "Ukázal mi svoje staré fotky.",
    perf_v: "Už ti Ján ukázal jeho nový byt?"
},
{
    img: "87.png",
    inf: "sew",
    tr_inf: "[səu]",
    pret: "sewed",
    tr_pret: "[səud]",
    perf: "sewn",
    tr_perf: "[səum]",
    inf_s: "She sews all her children's clothes.",
    pret_s: "I sewed on three buttons.",
    perf_s: "Have you sewn a patch on my jeans?",
    trans: "šiť",
    inf_v: "Ona šije oblečenie pre svoje detí.",
    pret_v: "Prišila som tri gombiky.",
    perf_v: "Prišila si mi na rifle záplatu? "
},
{
    img: "119.png",
    inf: "take",
    tr_inf: "[teik]",
    pret: "took",
    tr_pret: "[tuk]",
    perf: "taken",
    tr_perf: "[teikən]",
    inf_s: "I take the train to school every morning.",
    pret_s: "He took the car to the garage.",
    perf_s: "I haven't taken my holidays for one year.",
    trans: "brať, vziať",
    inf_v: "Každé ráno idem do školy vlákom.",
    pret_v: "Zobral auto do garáže.",
    perf_v: "Celý rok som si nevzal dovolenku."
},
{
    img: "124.png",
    inf: "throw",
    tr_inf: "[θrəu]",
    pret: "threw",
    tr_pret: "[θru:]",
    perf: "thrown",
    tr_perf: "[θrəun]",
    inf_s: "We throw away a lot of rubbish everyday.",
    pret_s: "John threw the ball to him.",
    perf_s: "He has already thrown it away.",
    trans: "hodiť, vrhnúť",
    inf_v: "Každý deň vyhadzujeme veľa odpadkov.",
    pret_v: "Ján mu hodil loptu.",
    perf_v: "On to už vyhodil."
},
{
    img: "130.png",
    inf: "withdraw",
    tr_inf: "[wið'dro:]",
    pret: "withdrew",
    tr_pret: "[wið'dru:]",
    perf: "withdrawn",
    tr_perf: "[wið'dro:n]",
    inf_s: "I withdraw more than $200 every month.",
    pret_s: "She withdrew the key from the door.",
    perf_s: "I would have withdrawn my remarks if you had apologizen.",
    trans: "vybrať (z účtu)",
    inf_v: "Mesačne vyberiem z účtu viac ako 200$.",
    pret_v: "Vybrala kľúč z dverí.",
    perf_v: "Keby si sa ospravedlnil, stiahol by som svoje poznámky."
},
{
    img: "132.png",
    inf: "write",
    tr_inf: "[rait]",
    pret: "wrote",
    tr_pret: "[rəut]",
    perf: "written",
    tr_perf: "[ritn]",
    inf_s: "My friend George sometimes writes to me.",
    pret_s: "Tom wrote this book a few years ago.",
    perf_s: "He has already written the letter.",
    trans: "písať, napísať",
    inf_v: "Môj kamarát Juraj mi občas píše.",
    pret_v: "Tom napísal túto knihu pred niekoľkými rokmi.",
    perf_v: "Už napísal ten list."
},
],
cat5:[{
    img: "7.png",
    inf: "bend",
    tr_inf: "[bend]",
    pret: "bent",
    tr_pret: "[bent]",
    perf: "bent",
    tr_perf: "[bent]",
    inf_s:"The road bends to the right.",
    pret_s:"He bent down to pick up her gloves.",
    perf_s: "She has bent her ski pole by accident.",
    trans: "ohnuť sa, zohnúť sa, prikrčiť",
    inf_v: "Cesta sa ohýba doprava.",
    pret_v: "Sklonil sa a zhvihol jej rukavice.",
    perf_v: "Omylom si ohla lyžiarsku palicu."
},
{
    img: "9.png",
    inf: "bind",
    tr_inf: "[baind]",
    pret: "bound",
    tr_pret: "[baund]",
    perf: "bound",
    tr_perf: "[baund]",
    inf_s:"This memory binds us together.",
    pret_s:"They bound her hands and feet and left.",
    perf_s: "The book is bound in a hard cover.",
    trans: "viazať, spájať",
    inf_v: "Táto spomienka nás spája.",
    pret_v: "Zviazali jej ruky a nohy odišli.",
    perf_v: "Kniha je viazaná v pevnom obale."
},
{
    img: "11.png",
    inf: "bleed",
    tr_inf: "[bli:d]",
    pret: "bled",
    tr_pret: "[bled]",
    perf: "bled",
    tr_perf: "[bled]",
    inf_s:"Your nose is bleeding.",
    pret_s:"She slowly bled to death.",
    perf_s: "I have bled like this before.",
    trans: "krvácať",
    inf_v: "Tvoj nos krváca.",
    pret_v: "Pomaly vykrvácala.",
    perf_v: "Už som predtým tákto krvácal."
},
{
    img: "14.png",
    inf: "breed",
    tr_inf: "[bri:d]",
    pret: "bred",
    tr_pret: "[bred]",
    perf: "bred",
    tr_perf: "[bred]",
    inf_s:"Our neighbours breed cattle and sheep.",
    pret_s:"Success bred a certain arrogance in his case.",
    perf_s: "Toads have bred successfully this yaer.",
    trans: "chovať, pestovať",
    inf_v: "Naši susedia chovajú hovädzí dobytok a ovce.",
    pret_v: "Úspech priniesol v jeho prípade určitú aroganciu.",
    perf_v: "Ropuchy sa tohto roku úspešne rozmnožili."
},
{
    img: "15.png",
    inf: "bring",
    tr_inf: "[briŋ]",
    pret: "brought",
    tr_pret: "[bro:t]",
    perf: "brought",
    tr_perf: "[bro:t]",
    inf_s:"My wife often bring work home.",
    pret_s:"He brought me fresh fruits.",
    perf_s: "What have you brought today?",
    trans: "priniesť",
    inf_v: "Moja žena často nosí prácu domov.",
    pret_v: "On mi priniesol čerstvé ovocie.",
    perf_v: "Čo si dnes priniesol?."
},
{
    img: "17.png",
    inf: "build",
    tr_inf: "[bild]",
    pret: "built",
    tr_pret: "[bilt]",
    perf: "built",
    tr_perf: "[bilt]",
    inf_s:"Some birds build their nests in grass.",
    pret_s:"My father built this house in 1980.",
    perf_s: "The school has recently built a new gym.",
    trans: "stavať, postaviť",
    inf_v: "Niektorí vtáci si stavajú hniezda v tráve.",
    pret_v: "Môj otec postavil tento dom v roku 1980.",
    perf_v: "Škola nedávno postavila novú telocvičňu."
},
{
    img: "18.png",
    inf: "burn",
    tr_inf: "[bə:n]",
    pret: "burnt",
    tr_pret: "[bə:nt]",
    perf: "burnt",
    tr_perf: "[bə:nt]",
    inf_s:"My skin burns easily in the sun.",
    pret_s:"The house burnt to the ground.",
    perf_s: "He's just burnt all the letters.",
    trans: "(z)horieť, (s)páliť, popáliť sa",
    inf_v: "Moja pokožka sa ľahko opali na slnku.",
    pret_v: "Dom padol popolom.",
    perf_v: "Prave spalil všetky listy."
},
{
    img: "20.png",
    inf: "buy",
    tr_inf: "[bai]",
    pret: "bought",
    tr_pret: "[bo:t]",
    perf: "bought",
    tr_perf: "[bo:t]",
    inf_s:"I buy newspappers daily.",
    pret_s:"My father bought me a new coat on Monday.",
    perf_s: "Have you bought any fruit?",
    trans: "kúpiť ",
    inf_v: "Denne kupujem noviny.",
    pret_v: "Otec mi v pondelok kupil nový kabát.",
    perf_v: "Kupil si nejaké ovocie?"
},
{
    img: "21.png",
    inf: "catch",
    tr_inf: "[kæč]",
    pret: "caught",
    tr_pret: "[ko:t]",
    perf: "caught",
    tr_perf: "[ko:t]",
    inf_s:"Can you catch a ball with your left hand?",
    pret_s:"Nancy caught the ball and ran away.",
    perf_s: "Adam is ill. He has caughta cold.",
    trans: "chytať",
    inf_v: "Dokážeš chytitť loptu ľavou rukou?",
    pret_v: "Nancy chytila loptu a utiekla.",
    perf_v: "Adam je chorý. Dostal nádchu."
},
{
    img: "24.png",
    inf: "creep",
    tr_inf: "[kri:p]",
    pret: "crept",
    tr_pret: "[krept]",
    perf: "crept",
    tr_perf: "[krept]",
    inf_s:"When a person creeps, they move slowly.",
    pret_s:"I crept into my room.",
    perf_s: "Occasional errors have crept into the book.",
    trans: "plaziť sa",
    inf_v: "Keď sa človek plazí, pohybuje sa pomaly.",
    pret_v: "Vplazil som sa do svojej izby.",
    perf_v: "Obcaš sa do knihy vplazi chýba."
},
{
    img: "26.png",
    inf: "deal",
    tr_inf: "[di:l]",
    pret: "dealt",
    tr_pret: "[delt]",
    perf: "dealt",
    tr_perf: "[delt]",
    inf_s:"We only deal with international companies.",
    pret_s:"You dealt with situation very effectively.",
    perf_s: "Chapter 3 has dealt with rasism in our country.",
    trans: "zaoberať sa, obchodovať",
    inf_v: "My obchodujeme len s medzinarodnými spoločnosťami.",
    pret_v: "Situáciu ste vyriešili veľmi efektívne.",
    perf_v: "Kapitola 3 sa zaoberala rasizmom v našej krajine."
},
{
    img: "27.png",
    inf: "dig",
    tr_inf: "[dig]",
    pret: "dug",
    tr_pret: "[dag]",
    perf: "dug",
    tr_perf: "[dag]",
    inf_s:"I regularly dig my flower-bed.",
    pret_s:"He dug a little hole ih the ground.",
    perf_s: "We have dug the garden all day.",
    trans: "kopať, ryť",
    inf_v: "Pravidelne okopávam svoj kvietinový záhon.",
    pret_v: "Vykopal malú dieru v zemi.",
    perf_v: "Rýľovali sme záhradu celý deň."
},
{
    img: "30.png",
    inf: "dream",
    tr_inf: "[dri:m]",
    pret: "dreamt",
    tr_pret: "[dremt]",
    perf: "dreamt",
    tr_perf: "[dreamt]",
    inf_s: "I often dream about flying.",
    pret_s: "I dreamt about you last night.",
    perf_s: "I've always dreamt about becoming an actress.",
    trans: "snívať",
    inf_v: "Často snívam o lietaní.",
    pret_v: "Minulú noc sa mi snívalo o tebe.",
    perf_v: "Vždy som snívala o tom, stať sa herečkou."
},
{
    img: "35.png",
    inf: "feed",
    tr_inf: "[fi:d]",
    pret: "fed",
    tr_pret: "[fed]",
    perf: "fed",
    tr_perf: "[fed]",
    inf_s: "Farmer feeds his rabbits (on) hay.",
    pret_s: "I fed the monkeys in the zoo.",
    perf_s: "Have you fed tha cat?",
    trans: "kŕmiť",
    inf_v: "Farmár kŕmi králoky senom.",
    pret_v: "Kŕmil som opice v zoo.",
    perf_v: "Nármil si mačku?"
},
{
    img: "36.png",
    inf: "feel",
    tr_inf: "[fi:l]",
    pret: "felt",
    tr_pret: "[felt]",
    perf: "felt",
    tr_perf: "[felt]",
    inf_s: "I feel that he doesn't like me.",
    pret_s: "I felt tired yesterday",
    perf_s: "I have felt happy all day.",
    trans: "cítiť (sa), mať pocit",
    inf_v: "Cítim, že on mam nemá rád.",
    pret_v: "Včera som sa cítil unavený.",
    perf_v: "Celý deň sa cítim šťastný."
},
{
    img: "37.png",
    inf: "fight",
    tr_inf: "[fait]",
    pret: "fought",
    tr_pret: "[fo:t]",
    perf: "fought",
    tr_perf: "[fought]",
    inf_s: "They fight for their rights.",
    pret_s: "My grandfather fought in World War II.",
    perf_s: "We have already fought two battles.",
    trans: "bojovať",
    inf_v: "Bojujú za svoje práva.",
    pret_v: "Môj dedo bojobal v druhej svetovej vojne.",
    perf_v: "Už sme vyhrali dve bitky."
},
{
    img: "38.png",
    inf: "find",
    tr_inf: "[faind]",
    pret: "found",
    tr_pret: "[faund]",
    perf: "found",
    tr_perf: "[faund]",
    inf_s: "I don't find that funny at all.",
    pret_s: "I found a wallet full of cash.",
    perf_s: "Daniel has recently found a new job.",
    trans: "nájsť, zistiť",
    inf_v: "Vôbec sa mi to nezdá vtipné.",
    pret_v: "Našiel som peňaženku plnú hotovosti.",
    perf_v: "Daniel si nedávno našiel novú prácu."
},
{
    img: "45.png",
    inf: "get",
    tr_inf: "[get]",
    pret: "got",
    tr_pret: "[got]",
    perf: "got",
    tr_perf: "[got]",
    inf_s: "Ella often gets flowers from her husband.",
    pret_s: "Stuart got a new job.",
    perf_s: "We haven't got your message yet.",
    trans: "dostať, získať",
    inf_v: "Ella často dostáva kvety od svojho manžela.",
    pret_v: "Stuart dostal novú prácu.",
    perf_v: "Ešte sme nedostali tvoj odkaz."
},
{
    img: "49.png",
    inf: "hang",
    tr_inf: "[hæŋ]",
    pret: "hung",
    tr_pret: "[haŋ]",
    perf: "hung",
    tr_perf: "[haŋ]",
    inf_s: "His picture hangs in the boardroom.",
    pret_s: "Caroline hung a flag from her balcony.",
    perf_s: "The walls of their bedroom were hung with oil paintings.",
    trans: "visieť, zavesiť",
    inf_v: "Jeho obraz visí v zasadacej miestnosti.",
    pret_v: "Caroline na svojom balkóne zavesila vlajku.",
    perf_v: "Steny ich spálne boli ozdobené olejomaľbami."
},
{
    img: "50.png",
    inf: "have/has",
    tr_inf: "[hæv, hæz]",
    pret: "had",
    tr_pret: "[hæd]",
    perf: "had",
    tr_perf: "[hæd]",
    inf_s: "I have (got) a date.",
    pret_s: "Alica had an accident.",
    perf_s: "I have had dinner already.",
    trans: "mať, vlastniť",
    inf_v: "Mám rande.",
    pret_v: "Alica mala nehodu.",
    perf_v: "Už som mala večeru. (Už som večerala.)"
},
{
    img: "51.png",
    inf: "hear",
    tr_inf: "[hiə]",
    pret: "heard",
    tr_pret: "[hə:d]",
    perf: "heard",
    tr_perf: "[hə:d]",
    inf_s: "We hear this song every night.",
    pret_s: "Sophia heard a noise outside.",
    perf_s: "I have heard the news.",
    trans: "počuť",
    inf_v: "Počujeme túto pieseň každú noc.",
    pret_v: "Sofia počula vonku hluk.",
    perf_v: "Počula som tieto správy."
},
{
    img: "54.png",
    inf: "hold",
    tr_inf: "[həuld]",
    pret: "held",
    tr_pret: "[held]",
    perf: "held",
    tr_perf: "[held]",
    inf_s: "Who holds the record rof the long jump?",
    pret_s: "She held a baby in her arms.",
    perf_s: "I haven't held a gun yet.",
    trans: "držať",
    inf_v: "Kto drží rekord v skoku do diaľky?",
    pret_v: "Držala dieťa v náručí.",
    perf_v: "Ešte som nedržal zbraň."
},
{
    img: "57.png",
    inf: "keep",
    tr_inf: "[ki:p]",
    pret: "kept",
    tr_pret: "[kept]",
    perf: "kept",
    tr_perf: "[kept]",
    inf_s: "I keep all my tickets as souvenirs.",
    pret_s: "I kept in touch with her.",
    perf_s: "Your boss has never kept his promise.",
    trans: "držať, dodržať, zostať",
    inf_v: "Nechávam si všetky lístky ako suveníry.",
    pret_v: "Ostal som s ňou v kontakte.",
    perf_v: "Tvoj šéf nikdy nedodržal svoj sľub."
},
{
    img: "58.png",
    inf: "kneel",
    tr_inf: "[ni:l]",
    pret: "knelt",
    tr_pret: "[nelt]",
    perf: "knelt",
    tr_perf: "[nelt]",
    inf_s: "The priest always kneels in front of the altar.",
    pret_s: "John knelt down beside his son.",
    perf_s: "She has knelt and begged for help.",
    trans: "kľačať, kľaknúť si",
    inf_v: "Kňaz vždy kľačí pred oltárom.",
    pret_v: "Ján si kľakol vedľa svojho syna.",
    perf_v: "Pokľakla a prosila o pomoc."
},
{
    img: "60.png",
    inf: "lay",
    tr_inf: "[lei]",
    pret: "laid",
    tr_pret: "[leid]",
    perf: "laid",
    tr_perf: "[leid]",
    inf_s: "Hens lay eggs.",
    pret_s: "He laid the book aside and fell asleep.",
    perf_s: "Cindy has always laid the table for lunch.",
    trans: "niesť, položiť",
    inf_v: "Sliepky nosia vajcia.",
    pret_v: "Odložil knihu a zaspal.",
    perf_v: "Cindy vždy prestiera stôl na obed."
},
{
    img: "61.png",
    inf: "lead",
    tr_inf: "[li:d]",
    pret: "led",
    tr_pret: "[led]",
    perf: "led",
    tr_perf: "[led]",
    inf_s: "He leads a dull life.",
    pret_s: "The hostess let us to our table.",
    perf_s: "The orchestra was led by a young conductor.",
    trans: "viesť",
    inf_v: "Vedie monotónny spôsob života.",
    pret_v: "Hosteska nás doviedla k nášmu stolu.",
    perf_v: "Orchester viedol mladý dirigent."
},
{
    img: "62.png",
    inf: "learn",
    tr_inf: "[lə:n]",
    pret: "learnt",
    tr_pret: "[lə:nt]",
    perf: "learnt",
    tr_perf: "[lə:nt]",
    inf_s: "Paul learnts languages quickly.",
    pret_s: "I learnt to play the piano at an early age.",
    perf_s: "My sister has learnt four languages.",
    trans: "učiť sa",
    inf_v: "Pavol sa rýchlo učí jazyky.",
    pret_v: "Naučila som sa hrať na klavíri v mladom veku.",
    perf_v: "Moja sestra sa naučila štyri jazyky."
},
{
    img: "63.png",
    inf: "leave",
    tr_inf: "[li:v]",
    pret: "left",
    tr_pret: "[left]",
    perf: "left",
    tr_perf: "[left]",
    inf_s: "I usually leave for work at seven in the morning.",
    pret_s: "George left the house by the back door.",
    perf_s: "She hasn't left for the meeting yet.",
    trans: "opustiť, odisť",
    inf_v: "Zvyčajne odchádzam do práce o siedmej ráno.",
    pret_v: "Juraj opustil dom zadným vchodom.",
    perf_v: "Ešte neodišla na schôdzku."
},
{
    img: "64.png",
    inf: "lend",
    tr_inf: "[lend]",
    pret: "lent",
    tr_pret: "[lent]",
    perf: "lent",
    tr_perf: "[lent]",
    inf_s: "Rolf often lends us money.",
    pret_s: "I lent her my dictionary.",
    perf_s: "I have just lent my phone to my friend.",
    trans: "požičať",
    inf_v: "Rolf nám často požičiava peniaze.",
    pret_v: "Požičala som jej svoj slovník.",
    perf_v: "Práve som požičala telefón svojmu priateľovi."
},
{
    img: "67.png",
    inf: "light",
    tr_inf: "[lait]",
    pret: "lit",
    tr_pret: "[lit]",
    perf: "lit",
    tr_perf: "[lit]",
    inf_s: "Her face lights up when she smiles.",
    pret_s: "I lit the candles on the birthday cake.",
    perf_s: "A room was brightly lit.",
    trans: "rozsvietiť, zapaliť",
    inf_v: "Keď sa usmeje, jej tvár sa rozsvieti.",
    pret_v: "Zapálil som sviečky na narodeninovej torte.",
    perf_v: "Izba bola jasne osvetlená."
},
{
    img: "68.png",
    inf: "lose",
    tr_inf: "[lu:z]",
    pret: "lost",
    tr_pret: "[lost]",
    perf: "lost",
    tr_perf: "[lost]",
    inf_s: "Harry often loses his keys.",
    pret_s: "They lost their way in the woods.",
    perf_s: "He has lost a lot of weight recently.",
    trans: "stratiť",
    inf_v: "Harry často stráca svoje kľúče.",
    pret_v: "Stratili cestu v lese.",
    perf_v: "V poslednom čase veľmi schudla."
},
{
    img: "69.png",
    inf: "make",
    tr_inf: "[meik]",
    pret: "made",
    tr_pret: "[meid]",
    perf: "made",
    tr_perf: "[meid]",
    inf_s: "She makes tea for breakfast every morning.",
    pret_s: "Alan made a telephone call yesterday evening.",
    perf_s: "Monica has made herself a new dress.",
    trans: "robiť, vyrobiť",
    inf_v: "Každé ráno robí na raňajky čaj.",
    pret_v: "Alan uskutočnil včera večer telefonický hovor.",
    perf_v: "Monika si vyrobila nové šaty."
},
{
    img: "70.png",
    inf: "mean",
    tr_inf: "[mi:n]",
    pret: "meant",
    tr_pret: "[ment]",
    perf: "meant",
    tr_perf: "[ment]",
    inf_s: "Money means everything to them.",
    pret_s: "You know what I meant.",
    perf_s: "I have meant to help you.",
    trans: "znamenať, mieniť",
    inf_v: "Peniaze pre nich znamenajú všetko.",
    pret_v: "Vieš, čo som myslel.",
    perf_v: "Mal som v úmysle ti pomôcť."
},
{
    img: "71.png",
    inf: "meet",
    tr_inf: "[mi:t]",
    pret: "met",
    tr_pret: "[met]",
    perf: "met",
    tr_perf: "[met]",
    inf_s: "We usually meet on Sunday afternoons.",
    pret_s: "She met him at the railway station.",
    perf_s: "I've never met your sister.",
    trans: "stretnúť",
    inf_v: "Zvyčajne sa stretávame v nedeľu poobede.",
    pret_v: "Stretla ho na železničnej stanici.",
    perf_v: "Nikdy som sa nestretla s tvojou sestrou."
},
{
    img: "73.png",
    inf: "pay",
    tr_inf: "[pei]",
    pret: "paid",
    tr_pret: "[peid]",
    perf: "paid",
    tr_perf: "[peid]",
    inf_s: "Jack usually pays by credit card.",
    pret_s: "Tom paid for the vacation last month.",
    perf_s: "Have you paid the telephone bill yet?",
    trans: "platiť",
    inf_v: "Jack zvyčajne platí kreditnou kartou.",
    pret_v: "Tom zaplatil za dovolenku minulý mesiac.",
    perf_v: "Už si zaplatil telefónny účet?"
},
{
    img: "81.png",
    inf: "say",
    tr_inf: "[sei]",
    pret: "said",
    tr_pret: "[sed]",
    perf: "said",
    tr_perf: "[sed]",
    inf_s: "I don't always say what I mean.",
    pret_s: "She said she wanted a dog.",
    perf_s: "Finally you have said that.",
    trans: "povedať",
    inf_v: "Nie vždy hovorím, čo si myslím.",
    pret_v: "Povedala, že chce psa.",
    perf_v: "Konečne si to povedal."
},
{
    img: "83.png",
    inf: "seek",
    tr_inf: "[si:k]",
    pret: "sought",
    tr_pret: "[so:t]",
    perf: "sought",
    tr_perf: "[so:t]",
    inf_s: "Parents often seek to shelter their children from outside influences.",
    pret_s: "She sought relief in drink.",
    perf_s: "They have sought help from the police.",
    trans: "hľadať, usilovať sa, požiadať",
    inf_v: "Rodičia sa často snažia chrániť svoje deti pred vonkajšími vplyvmi.",
    pret_v: "Hľadala úľavu v nápoji.",
    perf_v: "Požiadali o pomoc policiu."
},
{
    img: "84.png",
    inf: "sell",
    tr_inf: "[sel]",
    pret: "sold",
    tr_pret: "[səuld]",
    perf: "sold",
    tr_perf: "[səuld]",
    inf_s: "Do you sell flowers?",
    pret_s: "I sold my car to James",
    perf_s: "He has just sold him flat.",
    trans: "predávať",
    inf_v: "Predávate kvety?",
    pret_v: "Predal som svoje auto Jamesovi.",
    perf_v: "Práve predal svoj byt."
},
{
    img: "85.png",
    inf: "send",
    tr_inf: "[send]",
    pret: "sent",
    tr_pret: "[sent]",
    perf: "sent",
    tr_perf: "[sent]",
    inf_s: "My parents send me money every month.",
    pret_s: "The doctor sent me to a specialist.",
    perf_s: "Have you sent flowers to your mother yet?",
    trans: "poslať",
    inf_v: "Moji rodičia mi každý mesiac posielajú peniaze.",
    pret_v: "Môj lekár ma poslal k špecialistovi.",
    perf_v: "Už si poslala kvety svojej matke?"
},
{
    img: "89.png",
    inf: "shine",
    tr_inf: "[šain]",
    pret: "shone",
    tr_pret: "[šon]",
    perf: "shone",
    tr_perf: "[šon]",
    inf_s: "Clean this kitchen until it shines!",
    pret_s: "He shone the torch in my face.",
    perf_s: "The sun has shone brightly all afternoon.",
    trans: "svietiť, žiariť",
    inf_v: "Vyčisti túto kuchyňu, nech žiari!",
    pret_v: "Zasvietil mi baterkou do tváre.",
    perf_v: "Slnko svietilo jasne celé popoludnie."
},
{
    img: "90.png",
    inf: "shoot",
    tr_inf: "[šu:t]",
    pret: "shot",
    tr_pret: "[šot]",
    perf: "shot",
    tr_perf: "[šot]",
    inf_s: "The police reraly shoot to kill.",
    pret_s: "He shot at her twice.",
    perf_s: "The outdoor scenes were shot in the Alps.",
    trans: "strieľať, zastreliť, fotiť",
    inf_v: "Policia zriedka niekoho zastreli.",
    pret_v: "Strelil na ňu dvakrát.",
    perf_v: "Vonkajšie scény boli nafotené v Alpách."
},
{
    img: "96.png",
    inf: "sit",
    tr_inf: "[sit]",
    pret: "sat",
    tr_pret: "[sæt]",
    perf: "sat",
    tr_perf: "[sæt]",
    inf_s: "Olivia sits next to me at school.",
    pret_s: "Philip sat and looked at the pictures.",
    perf_s: "She has just sat down on the chair.",
    trans: "sedieť",
    inf_v: "Olivia sedí v škole vedľa mňa.",
    pret_v: "Filip sedel a pozeral sa na obrázky.",
    perf_v: "Práve sa posadila na stoličku."
},
{
    img: "97.png",
    inf: "sleep",
    tr_inf: "[sli:p]",
    pret: "slept",
    tr_pret: "[slept]",
    perf: "slept",
    tr_perf: "[slept]",
    inf_s: "I usually sleep on my side.",
    pret_s: "Eric slept till ten in the morning.",
    perf_s: "I have not slept well since the accident.",
    trans: "spať",
    inf_v: "Zvyčajne spím na boku.",
    pret_v: "Erik spal do desiatej rána.",
    perf_v: "Od tej nehody nespím dobre."
},
{
    img: "98.png",
    inf: "slide",
    tr_inf: "[slaid]",
    pret: "slid",
    tr_pret: "[slid]",
    perf: "slid",
    tr_perf: "[slid]",
    inf_s: "The drawers slide in and out easily.",
    pret_s: "She slid the letter into her apron pocket.",
    perf_s: "The car has slid into the ditch.",
    trans: "vsunúť, skĺznuť",
    inf_v: "Šuplíky sa ľahko zasúvajú a vysúvajú.",
    pret_v: "Vsunúla ten list do vrecka na zastiere.",
    perf_v: "Auto skĺzlo do priekopy."
},
{
    img: "99.png",
    inf: "smell",
    tr_inf: "[smel]",
    pret: "smelt",
    tr_pret: "[smelt]",
    perf: "smelt",
    tr_perf: "[smelt]",
    inf_s: "Your dinner always smells delicious.",
    pret_s: "Her hands smelt of fish.",
    perf_s: "The dog has smelt a rabbit.",
    trans: "cítiť, voňať",
    inf_v: "Tvoja večera vonia vždy výborne.",
    pret_v: "Z jej rúk bolo cítiť ryby.",
    perf_v: "Pes zacítil králika."
},
{
    img: "101.png",
    inf: "spell",
    tr_inf: "[spel]",
    pret: "spelt",
    tr_pret: "[spelt]",
    perf: "spelt",
    tr_perf: "[spelt]",
    inf_s: "How do you spell your surname?",
    pret_s: "You spelt most words wrong.",
    perf_s: "Have I spelt your name right?",
    trans: "hláskovať",
    inf_v: "Ako vyhláskuješ tvoje priezvisko?",
    pret_v: "Väčšinu slov ste vyhláskoval nespávne.",
    perf_v: "Vyhláskoval som tvoje meno správne?"
},
{
    img: "102.png",
    inf: "spend",
    tr_inf: "[spend]",
    pret: "spent",
    tr_pret: "[spent]",
    perf: "spent",
    tr_perf: "[spent]",
    inf_s: "I often spend a lot of money on parties.",
    pret_s: "Lucy spent two hours on the phone that day.",
    perf_s: "John has spent most of his time at work lately.",
    trans: "stráviť, utratiť",
    inf_v: "Často utrácam veľa peňazi za večierky.",
    pret_v: "Lucia strávila ten deň dve hodiny telefonovaním.",
    perf_v: "Ján trávi v poslednej dobe väčšinu času v práci."
},
{
    img: "103.png",
    inf: "spill",
    tr_inf: "[spil]",
    pret: "spilt",
    tr_pret: "[spilt]",
    perf: "spilt",
    tr_perf: "[spilt]",
    inf_s: "I always spill coffee on my shirt.",
    pret_s: "Katie almost spilt her milk.",
    perf_s: "His toys have split out of the basket.",
    trans: "rozliať, vysypať",
    inf_v: "Vždy vylejem kavu na košeľu.",
    pret_v: "Katie skoro vyliala svoje mlieko.",
    perf_v: "Jeho hračky sa vysypali z koša."
},
{
    img: "105.png",
    inf: "spoil",
    tr_inf: "[spoil]",
    pret: "spoilt",
    tr_pret: "[spoilt]",
    perf: "spoilt",
    tr_perf: "[spoilt]",
    inf_s: "His mother spoilts him with toys.",
    pret_s: "There was a power cut yesterday and all the food spoilt.",
    perf_s: "Our trip was spoilt by bad weather.",
    trans: "pokaziť (sa), rozmaznávať",
    inf_v: "Jeho matka ho rozmaznáva hračkami.",
    pret_v: "Včera došlo k výpadu elektrickej energie a jedlo sa pokazilo.",
    perf_v: "Náš výlet pokazilo zlé počasie."
},
{
    img: "107.png",
    inf: "spring",
    tr_inf: "[spriŋ]",
    pret: "sprang",
    tr_pret: "[spræŋ]",
    perf: "sprung",
    tr_perf: "[spraŋ]",
    inf_s: "He springs out of bed every morning.",
    pret_s: "Tears sprang to her eyes.",
    perf_s: "The cat has sprung onto the table.",
    trans: "vyskočiť, objaviť sa",
    inf_v: "On každé ráno vyskočí z postele.",
    pret_v: "Na jej očiach sa objavili slzy.",
    perf_v: "Mačka vyskočila na stôl."
},
{
    img: "108.png",
    inf: "stand",
    tr_inf: "[stænd]",
    pret: "stood",
    tr_pret: "[stud]",
    perf: "stood",
    tr_perf: "[stud]",
    inf_s: "The building stands on the corner.",
    pret_s: "The Chrismas tree stood near the window.",
    perf_s: "I have stood here for five minutes already.",
    trans: "stáť",
    inf_v: "Tá budova stojí na rohu.",
    pret_v: "Vianočný stromček stál blízko okna.",
    perf_v: "Už tu stojím päť minút."
},
{
    img: "110.png",
    inf: "stick",
    tr_inf: "[stik]",
    pret: "stuck",
    tr_pret: "[stak]",
    perf: "stuck",
    tr_perf: "[stak]",
    inf_s: "The store sticks price labels directly on fruit.",
    pret_s: "The old lady stuck her knitting needles into a ball of wool.",
    perf_s: "The wheels have stuck in the mud.",
    trans: "(pri)lepiť, pichať, uviaznuť",
    inf_v: "V tom obchode lepia cenovky priamo na ovocie.",
    pret_v: "Stará dáma napichla svoje ihlice do vlny.",
    perf_v: "Kolesa uviazli v blate."
},
{
    img: "111.png",
    inf: "sting",
    tr_inf: "[stiŋ]",
    pret: "stung",
    tr_pret: "[staŋ]",
    perf: "stung",
    tr_perf: "[staŋ]",
    inf_s: "Do all types of bee sting?",
    pret_s: "A wasr stung me yesterday.",
    perf_s: "What has stung you?",
    trans: "pichnúť, bodnúť",
    inf_v: "Bodajú všetky druhy včiel?",
    pret_v: "Včera ma bodla osa.",
    perf_v: "Čo ťa pichlo?"
},
{
    img: "115.png",
    inf: "sweep",
    tr_inf: "[swi:p]",
    pret: "swept",
    tr_pret: "[swept]",
    perf: "swept",
    tr_perf: "[swept]",
    inf_s: "A new broom sweeps clean.",
    pret_s: "I swept snow from the steps.",
    perf_s: "Have you swept the kitchen floor yet?",
    trans: "(po)zametať",
    inf_v: "Nová metla dobre zametá.",
    pret_v: "Zamietol som sneh zo schodov.",
    perf_v: "Už si pozametal kuchynskú podlahu?"
},
{
    img: "118.png",
    inf: "swing",
    tr_inf: "[swiŋ]",
    pret: "swung",
    tr_pret: "[swaŋ]",
    perf: "swung",
    tr_perf: "[swaŋ]",
    inf_s: "She swings her hips as she walks.",
    pret_s: "He swung on the garden swing.",
    perf_s: "The pendulum has swung back and forth.",
    trans: "hojdať sa",
    inf_v: "Počas chôdze sa hojdajú boky.",
    pret_v: "Pohojdal sa na zahradnej hojdačke.",
    perf_v: "Kyvadlo sa hojdalo tam a späť."
},
{
    img: "120.png",
    inf: "teach",
    tr_inf: "[ti:č]",
    pret: "taught",
    tr_pret: "[to:t]",
    perf: "taught",
    tr_perf: "[to:t]",
    inf_s: "My schoolmate teaches me how to sing.",
    pret_s: "She taught me how to dance.",
    perf_s: "Life has taught me to work hard.",
    trans: "učiť, vyučovať",
    inf_v: "Môj spolužiak ma učí spievať.",
    pret_v: "Naučila ma tancovať.",
    perf_v: "Život ma naučil tvrdo pracovať."
},
{
    img: "122.png",
    inf: "tell",
    tr_inf: "[tel]",
    pret: "told",
    tr_pret: "[təuld]",
    perf: "told",
    tr_perf: "[təuld]",
    inf_s: "She tells that story to everyone she sees.",
    pret_s: "Alice told me about their trip yesterday.",
    perf_s: "Have you told anyone about this?",
    trans: "povedať",
    inf_v: "Rozpráva ten príbeh každému, koho stretne.",
    pret_v: "Alice mi včera povedala o ich výlete.",
    perf_v: "Povedal si o tom niekomu?"
},
{
    img: "123.png",
    inf: "think",
    tr_inf: "[θɪŋk]",
    pret: "thought",
    tr_pret: "[θo:t]",
    perf: "thought",
    tr_perf: "[θo:t]",
    inf_s: "What do you think about it?",
    pret_s: "I thought about the problem for a long time.",
    perf_s: "I have thought of you all day long.",
    trans: "myslieť",
    inf_v: "Čo si o tom myslíš?",
    pret_v: "Premýšľal som o tom probléme dlhý čas.",
    perf_v: "Myslím na teba celý deň."
},
{
    img: "125.png",
    inf: "understand",
    tr_inf: "[andə'stænd]",
    pret: "understood",
    tr_pret: "[andə'stud]",
    perf: "understood",
    tr_perf: "[andə'stud]",
    inf_s: "Our children understand each other well.",
    pret_s: "I spoke English, but noboody understood me.",
    perf_s: "I haven't understood his explanation.",
    trans: "rozumieť",
    inf_v: "Naše deti si dobre rozumejú.",
    pret_v: "Hovoril som po anglicky, ale nikto mi nerozumel.",
    perf_v: "Nerozumel som jeho vysvetleniu."
},
{
    img: "128.png",
    inf: "weep",
    tr_inf: "[wi:p]",
    pret: "wept",
    tr_pret: "[wept]",
    perf: "wept",
    tr_perf: "[wept]",
    inf_s: "I always weep when I see this film.",
    pret_s: "Alice wept for joy.",
    perf_s: "He has never wept in front of other people.",
    trans: "plakať",
    inf_v: "Vždy plačem, keď vidím tento film.",
    pret_v: "Alica plakala od radosti.",
    perf_v: "Nikdy neplakal pred inými ľuďmi."
},
{
    img: "129.png",
    inf: "win",
    tr_inf: "[win]",
    pret: "won",
    tr_pret: "[wan]",
    perf: "won",
    tr_perf: "[wan]",
    inf_s: "Their team always wins all the matches.",
    pret_s: "He won a lot of money.",
    perf_s: "Who has won the race this time?",
    trans: "vyhrať",
    inf_v: "Ich tím vždy vyhrá všetky zápasy.",
    pret_v: "Vyhral veľa peňazí.",
    perf_v: "Kto vyhral tie preteky tentoraz?"
},
{
    img: "131.png",
    inf: "wring",
    tr_inf: "[riŋ]",
    pret: "wrung",
    tr_pret: "[raŋ]",
    perf: "wrung",
    tr_perf: "[raŋ]",
    inf_s: "He wring his hands when he's nervous.",
    pret_s: "My grandmother wrung the chicken's neck.",
    perf_s: "I have wrung out my clothes.",
    trans: "žmýkať, zalamovať, vykrútiť",
    inf_v: "Keď je nervózny, zalamuje ruky.",
    pret_v: "Moja babka vykrútila sliepke krk.",
    perf_v: "Vyžmýkala som si šaty."
},

]}