var missions = [
        {
    "status":["Misie",
              "Misie",
              "Misie",
              "Misie",
              "Misie",
              "Obnova",
              "Misie",
              "Misie",
              "Misie",
              "Misie",
              "Misie"],
    "plan":"Plán misií",
    "show":false,
    "mapa":"Mapa misií",
    "mapa_link":"img/svg/misie1994.svg",
    "year":1994,
    "diecezis": ["Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Banskobystrická diecéza"],
    "admin":["František Gurecka",
             "Anton Hrtus",
             "Ľudovít Štepecký",
             "Vladimír Fajkus",
             "Štefan Saloka",
             "Ladislav Herman",
             "Michal Regec",
             "Marián Pánik",
             "Štefan Koma",
             "Ján Čuchran",
             "Juraj Dubec"

           ],
    "date":["27. 2. - 6. 3.",
            "13. 3 - 20. 3",
            "16. 4. - 24. 4.",
            "7. 5. - 14. 5.",
            "4. 6. - 12. 6.",
            "13. 6. - 16. 6.",
            "17. 9. - 25. 9.",
            "8. 10. - 16. 10.",
            "22. 10. - 30. 10.",
            "5. 11. - 13. 11.",
            "3. 12. - 11. 12."],
    "missionars":[["img/mis/mz1.svg", "img/mis/mm1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/if1.svg","img/mis/vc1.svg","img/mis/mm1.svg","img/mis/jd1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm1.svg", "img/mis/jd1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm1.svg", "img/mis/jd1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm1.svg", "img/mis/jd1.svg"],
                  ["img/mis/mz1.svg","img/mis/mm1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm1.svg","img/mis/ps1.svg","img/mis/jt1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm1.svg","img/mis/vh1.svg","img/mis/sv1.svg", "img/mis/ps1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm1.svg"],
                  ["img/mis/mz1.svg","img/mis/mm1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/sv1.svg","img/mis/ps1.svg","img/mis/jj1.svg","img/mis/mk1.svg"]
                  ],
    "citys":["Lesnica",
             "Lendak",
             "Ždiar",
             "Hniezdne",
             "Vyšné Ružbachy",
             "Považská Bystrica",
             "Liptovské Revúce",
             "Tvrdošín","Liesek",
             "Hnilec",
             "Bojnice"],
  },
  {
    "status":["Misie",
              "Misie",
              "Misie",
              "Obnova",
              "Misie",
              "Obnova",
              "Misie",
              "Obnova",
              "Obnova",
              "Misie",
              "Misie",
              "Misie",
              "Obnova",
              "Obnova",
              "Misie",
              "Misie",
              "Misie",
              "Obnova",
              "Misie"],
    "plan":"Plán misií",
    "show":false,
    "mapa":"Mapa misií",
    "mapa_link":"img/svg/misie1995.svg",
    "year":1995,
    "diecezis": ["Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza"],
    "admin":["Andrej Konc",
             "",
             "",
             "",
             "",
             "",
             "Michal Tondra",
             "",
             "",
             "Jozef Vrbovský",
             "Ján Hrabovský",
             "Jozef Jurina",
             "Štefan Koma",
             "Michal Regec",
             "Ján Kuboš",
             "Marek Kosorín",
             "Jozef Pataky",
             "Ľudovít Frič",
             "Jozef Grich"
           ],
    "date":["14. 1. - 22. 1.",
            "4. 2. - 12. 2.",
            "18. 2. - 26. 2.",
            "26. 2. - 1. 3.",
            "4. 3. - 12. 3.",
            "19. 3. - 23. 3.",
            "25. 3. - 2. 4.",
            "23. 4. - 27. 4.",
            "30. 4. - 4. 5.",
            "6. 5. - 15. 5.",
            "10. 6. - 18. 6.",
            "9. 9. - 17. 9.",
            "24. 9. - 28. 9.",
            "1. 10. - 5. 10.",
            "7. 10. - 15. 10.",
            "21. 10. - 29. 10.",
            "4. 11. - 12. 11.",
            "19. 11. - 23. 11.",
            "2. 12. - 10. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/jj1.svg","img/mis/mk1.svg"],
                  ["img/mis/mz1.svg", "img/mis/sv1.svg"],
                  [],
                  [],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/sv1.svg","img/mis/mk1.svg"],
                  [],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/vh1.svg"],
                  [],
                  [],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/sv1.svg","img/mis/mk1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/vh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg"],
                  [],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg"],
                  [],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/ps1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/ps1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/ps1.svg"]
                 ],
    "citys":["Kechnec",
             "Pavlovce nad Úhom",
             "Lechnica",
             "Lesnica",
             "Spišský Hrhov",
             "Lendak",
             "Trstená",
             "Ždiar",
             "Hniezdne",
             "Námestovo",
             "Stará Bystrica",
             "Vrbové",
             "Liesek",
             "Liptovské Revúce",
             "Liptovská Osada",
             "Žitavany",
             "Podolínec",
             "Tvrdošín",
             "Kežmarok"],
  },
  {
    "status":["Misie",
              "Misie",
              "Misie",
              "Misie",
              "Misie",
              "Misie",
              "Misie",
              "Misie",
              "Misie",
              "Misie",
              "Misie"],
    "plan":"Plán misií",
    "show":false,
    "mapa":"Mapa misií",
    "mapa_link":"img/svg/misie1996.svg",
    "year":1996,
    "diecezis": ["Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Rožňavská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Spišská diecéza"],
    "admin":["",
             "",
             "Ján Farkašovský",
             "",
             "Marián Pánik",
             "František Mašľár",
             "Stanislav Cifra",
             "Ladislav Drengubjak",
             "Jozef Golvoň",
             "Jaroslav Špeťko",
             "Roland Ferenc"
  ],
    "date":["21. 1 - 28. 1.",
            "3. 2. - 11. 2.",
            "24. 2. - 3. 3.",
            "16. 3. - 24. 3.",
            "20. 4. - 28. 4.",
            "4. 5. - 12. 5.",
            "1. 6. - 9. 6.",
            "12. 10. - 20. 10.",
            "2. 11. - 10. 11.",
            "23. 11. - 1. 12.",
            "7. 12. - 15. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/ps1.svg"],
                  [],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/ps1.svg"],
                  [],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/ps1.svg"],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/sv1.svg","img/mis/ps1.svg", "img/mis/jb1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  [],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg"],
                  [],
                  []

                  ],
    "citys":["Veľká Lomnica",
             "Liptovský Mikuláš",
             "Nižná na Orave",
             "Spišské Vlachy",
             "Stará Ľubovňa",
             "Plavnica",
             "Prakovce",
             "Oravské Veselé",
             "Hladovka",
             "Nové Mesto nad Váhom",
             "Odorín"],
  },
  {
    "status":["Misie",
              "Obnova",
              "Misie",
              "Obnova",
              "Misie",
              "Obnova",
              "Misie",
              "Misie",
              "Obnova",
              "Misie",
              "Obnova",
              "Misie",
              "Misie",
              "Misie",
              "Misie"],
    "plan":"Plán misií",
    "show":false,
    "mapa":"Mapa misií",
    "mapa_link":"img/svg/misie1997.svg",
    "year":1997,
    "diecezis": ["Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Spišská diecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Rožňavská diecéza"],
    "admin":["???",
             "???",
             "Peter Fedorowicz",
             "Jozef Grich",
             "Marián Hovanec",
             "Michal Tondra",
             "Zdenko Sitka",
             "Ľubomír Štefaňák",
             "Ján Farkašovský",
             "Jaroslav Kmeť",
             "Blažej Dibdiak",
             "Cyril Lieskovský",
             "Ľubomír Zavacký",
             "Štefan Sojčák",
             "Štefan Magút"
  ],
    "date":["18. 1. - 26. 1.",
            "2. 2. - 6. 2.",
            "22. 2. - 2. 3.",
            "9. 3. - 13. 3.",
            "12. 4. - 20. 4.",
            "11. 5. - 15. 5.",
            "24. 5. - 1. 6.",
            "7. 6. - 15. 6.",
            "31. 8. - 4. 9.",
            "13. 9. - 21. 9.",
            "28. 9. - 2. 10.",
            "11. 10. - 19. 10.",
            "8. 11. - 16. 11.",
            "22. 11. - 30. 11.",
            "7. 12. - 14. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/sv1.svg"],
                  [],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/mm1.svg", "img/mis/ps1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  [],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg"],
                  [],
                  [],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],

  ],
    "citys":["Podbiel",
             "Liptovský Mikuláš",
             "Trenčianska Teplá",
             "Kežmarok",
             "Bratislava - Kalvária",
             "Trstená",
             "Smolenice",
             "Hranovnica",
             "Nižná na Orave",
             "Bielý Potok",
             "Námestovo",
             "Štiavnik",
             "Svit",
             "Brezovica",
             "Mnišek nad Hnilcom"],
  },
  {
    "status":["Misie",
              "Obnova",
              "Misie",
              "Misie",
              "Obnova",
              "Misie",
              "Misie",
              "Obnova",
              "Misie",
              "Obnova",
              "Misie",
              "Misie",
              "Misie",
              "Misie",
              "Misie"],
    "plan":"Plán misií",
    "show":false,
    "mapa":"Mapa misií",
    "mapa_link":"img/svg/misie1998.svg",
    "year":1998,
    "diecezis": ["Spišská diecéza",
                 "Nitrianska diecéza",
                 "Rožňavská diecéza",
                 "Nitrianska diecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Bratislavsko-trnavská diecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Bratislavsko-trnavská diecéza",
                 "Spišská diecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Banskobystrická diecéza",
                 ],
    "admin":["Ján Hlavčák",
             "Jozef Hlinka",
             "Štefan Kosturko",
             "Jozef Gánovský",
             "Marián Hovanec",
             "Ondrej Palušák",
             "Juraj Petrík",
             "Jozef Jurina",
             "František Šándor",
             "Ľubomír Zavacký",
             "Vendelín Pleva",
             "Franciszek Piosek",
             "Kalabus Pavol",
             "Michal Mikula",
             "Jozef Figur"
  ],
    "date":["17. 1. - 25. 1.",
            "31. 1. - 5. 2.",
            "14. 2. - 22. 2.",
            "14. 3. - 22. 3.",
            "28. 3. - 2. 4.",
            "25. 4. - 3. 5.",
            "9. 5. - 17. 5.",
            "23. 5. - 28. 5.",
            "12. 9. - 20. 9.",
            "26. 9. - 1. 10.",
            "10. 10 - 18. 10.",
            "24. 10. - 1. 11.",
            "14. 11. - 22. 11.",
            "28. 11. - 6. 12.",
            "12. 12. - 20. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/if1.svg","img/mis/vm1.svg"]

  ],
    "citys":["Oravský Biely Potok",
             "Trenčianska Teplá",
             "Krompachy",
             "Nová Dubnica",
             "Bratislava - Kalvária",
             "Iliašovce",
             "Sobrance",
             "Vrbové",
             "Vranov nad Topľou - Juh",
             "Svit",
             "Stará Turá",
             "Breza",
             "Veľké Rovné",
             "Spišský Štiavnik",
             "Nedožery - Brezany"],
  },
  {
    "status":["Misie",
              "Obnova",
              "Obnova",
              "Misie",
              "Misie",
              "Obnova",
              "Obnova",
              "Misie  ",
              "Misie",
              "Obnova",
              "Misie",
              "Misie",
              "Misie",
              "Misie"],
    "plan":"Plán misií",
    "show":false,
    "mapa":"Mapa misií",
    "mapa_link":"img/svg/misie1999.svg",
    "year":1999,
    "diecezis": ["Košická arcidiecéza",
                 "Rožňavská diecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Nitrianska diecéza",
                 "Košická arcidiecéza",
                 "Rožňavská diecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Spišská diecéza",
                 "Nitrianska diecéza",
                 "Košická arcidiecéza"],
    "admin":["Stanislav Palenčár ",
             "Štefan Kosturko",
             "Jozef Gánovský",
             "Alfonz Letanovký",
             "Martin Koleják",
             "Cyril Lieskovský",
             "Juraj Petrík",
             "Ján Kundrík",
             "Andrej Šinaľ",
             "František Šandor",
             "Štefan Herényi",
             "Jozef Šimurdiak",
             "Peter Hluzák",
             "Róbert Lapko"
  ],
    "date":["16. 1. - 24. 1.",
            "30. 1. - 4. 2.",
            "13. 2. - 18. 2.",
            "27. 2. - 7. 3.",
            "17. 4. - 25. 4.",
            "1. 5. - 6. 5.",
            "15. 5. - 20. 5.",
            "29. 5. - 6. 6.",
            "11. 9. - 19. 9.",
            "25. 9. - 30. 9.",
            "9. 10 - 17. 10.",
            "30. 10. - 7. 11.",
            "20. 11. - 28. 11.",
            "11. 11. - 19. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"]
  ],
    "citys":["Belá nad Cirochou",
             "Krompachy",
             "Nová Dubnica",
             "Dolný Kubín",
             "Sihelné a Oravská Polhora",
             "Štiavnik",
             "Sobrance",
             "Gelnica",
             "Košice - Nad Jazerom",
             "Vranov nad Topľou - Juh",
             "Bratislava - Blumenál",
             "Poprad - Matejovce",
             "Horná Súča",
             "Košické Olšany"],
  },
{
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Obnova",
               "Obnova",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show":false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2000.svg",
    "year" : 2000,
    "diecezis": ["Spišská diecéza",
                 "Banskobystrická diecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Banskobystrická diecéza",
                 "Spišská diecéza",
                 "Banskobystrická diecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Košická arcidiecéza",
                 "Olomoucká arcidiecéza",
                 "Nitrianska diecéza",
                 "Nitrianska diecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Bratislavsko-trnavská arcidiecéza"],
    "admin":["Vladimír Hanula",
             "Marián Holbay",
             "Stanislav Novotný",
             "Michal Tkáč",
             "Albert Bak",
             "Alfonz Letanovký",
             "Ján Kundrík",
             "Peter Slepčán",
             "Peter Rákoš",
             "Richard Wojciechowski",
             "Marián Javor",
             "Ivan Pšenák",
             "Tibor Závadský",
             "Jozef Červeň",
             "František Čonka",
             "Andrej Barnáš",
             "Marián Gáborík"
  ],
    "date" : ["8. 1. - 16. 1.",
              "22. 1. -  30. 1.",
              "5. 2. -  13. 2.",
              "4. 3. -  12. 3.",
              "18. 3. -  26. 3.",
              "1. 4. -  6. 4.",
              "29. 4. -  4. 5.",
              "13. 5. -  21. 5.",
              "27. 5. -  4. 6.",
              "17. 6. -  25. 6.",
              "9. 9. -  17. 9.",
              "23. 9. -  1. 10.",
              "14. 10. -  22. 10.",
              "28. 10. -  5. 11.",
              "11. 11. -  19. 11.",
              "25. 11. -  3. 12.",
              "9. 12. -  17. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg","img/mis/vc1.svg","img/mis/pg1.svg",],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/rb1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/mm1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg","img/mis/mm1.svg","img/mis/pg1.svg",],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vm1.svg","img/mis/pg1.svg",],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/sv1.svg","img/mis/vm1.svg","img/mis/pg1.svg",],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/sv1.svg","img/mis/mm1.svg","img/mis/pg1.svg",],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/sv1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/sv1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/mp1.svg",]
  ],
    "citys" : ["Nová Ľubovňa",
               "Martin - Sever",
               "Raslavice",
               "Rozhanovce",
               "Zvolen - Západ",
               "Dolný Kubín",
               "Gelnica",
               "Bratislava - Dóm",
               "Ražňany",
               "Nedašov (ČR)",
               "Zlaté Moravce",
               "Varín",
               "Košice - Juh",
               "Toporec",
               "Ohradzany",
               "Hrabušice",
               "Budmerice"],
  },
{
    "status": ["Obnova",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Obnova",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2001.svg",
    "year" : 2001,
    "diecezis": ["Spišská diecéza",
                 "Spišská diecéza",
                 "Rožňavská diecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Nitrianska diecéza",
                 "Košická arcidiecéza",
                 "Nitrianska diecéza",
                 "Kauno arcidiecéza",
                 "Riga arcidiecéza",
                 "Spišská diecéza"
  ],
    "admin":["Ondrej Palušák",
             "Peter Palider",
             "Ignác Kelemen",
             "Jozef Garaj",
             "Peter Paliatka",
             "Ján Bíroš",
             "Marián Javor",
             "",
             "",
             "Štefan Saloha"
  ],
    "date" : ["17. 1. - 19. 1.",
              "20. 1. -  28. 1.",
              "17. 2. -  25. 2.",
              "10. 3. -  18. 3.",
              "24. 3. -  1. 4.",
              "5. 5. -  13. 5.",
              "26. 5. -  31. 5.",
              "1. 7. -  7. 7.",
              "8. 7. -  14. 7.",
              "8. 12. -  16. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/vm1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/jj1.svg","img/mis/rd1.svg","img/mis/mp1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/mm1.svg","img/mis/ps1.svg","img/mis/vm1.svg",],
                  ["img/mis/mz1.svg","img/mis/mm1.svg","img/mis/vh1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm1.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg"],
                  ["img/mis/mz1.svg"],
                  ["img/mis/mz1.svg","img/mis/mm1.svg","img/mis/vh1.svg","img/mis/pg1.svg"],
  ],
    "citys" : ["Iliašovce",
               "Oravská Jasenica",
               "Rožňava",
               "Bratislava - Ružinov",
               "Trenčín",
               "Dubovica",
               "Zlaté Moravce",
               "Litva - Kaunas",
               "Lotyšsko - Riga",
               "Nižné Ružbachy"],
  },
{
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Obnova",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Obnova",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2002.svg",
    "year" : 2002,
    "diecezis": ["Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Olomoucká arcidiecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza"
  ],
    "admin":["Juraj Riško",
             "Stanislav Stolárik",
             "Ľubomír Zavacký",
             "Marián Vojtko",
             "Jozef Garaj",
             "Martin Poživenec",
             "František Dlugoš",
             "Richard Wojciechowski",
             "František Duda",
             "Stanislav Novotný",
             "Michal Keblušek",
             "Viliam Maretta",
             "Vladimír Dzurenda"

  ],
    "date" : ["16. 2. - 24. 2.",
              "9. 3. -  17. 3.",
              "6. 4. -  14. 4.",
              "20. 4. -  28. 4.",
              "11. 5. -  16. 5.",
              "25. 5. -  2. 6.",
              "31. 8. -  8. 9.",
              "21. 9. -  29. 9.",
              "12. 10. - 20. 10.",
              "26. 10. -  2. 11.",
              "9. 11. -  17. 11.",
              "23. 11. -  1. 12.",
              "7. 12. -  15. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vc1.svg","img/mis/jj1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/sv1.svg","img/mis/jj1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/sv1.svg","img/mis/vh1.svg","img/mis/vm1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/js1.svg","img/mis/vh1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/js1.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg"],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/fr1.svg","img/mis/vc1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/mh1.svg","img/mis/js1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/mh1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/mh1.svg","img/mis/pg1.svg"],

  ],
    "citys" : ["Víťaz",
               "Prešov",
               "Spišské Bystré",
               "Myjava",
               "Bratislava - Ružinov",
               "Orechové",
               "Levoča",
               "Brumov (ČR)",
               "Michalovce",
               "Raslavice",
               "Rajec",
               "Rabčice",
               "Spišská Belá"],
  },
{
    "status": ["Misie",
               "Obnova",
               "Misie",
               "Misie",
               "Obnova",
               "Misie",
               "Obnova",
               "Obnova",
               "Misie",
               "Misie",
               "Obnova",
               "Obnova",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2003.svg",
    "year" : 2003,
    "diecezis": ["Rožňavská diecéza",
                 "Košická arcidiecéza",
                 "Rožňavská diecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Spišská diecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Rožňavská diecéza",
                 "Olomoucká diecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Košická arcidiecéza"
  ],
    "admin":["Anton Mazán",
             "Juraj Riško",
             "Dušan Mesík",
             "Jaroslav Naščák",
             "Stanislav Stolárik",
             "Peter Olekšák",
             "Marián Vojtko",
             "František Dlugoš",
             "Peter Hoľbička",
             "Pavol Lacko",
             "Anton Mazán",
             "Mirek Sleldzinski",
             "Ján Hallon",
             "Stanislav Ferčák"
  ],
    "date" : ["11. 1. - 19. 1.",
              "1. 2. -  6. 2.",
              "15. 2. -  23. 2.",
              "8. 3. -  16. 3.",
              "5. 4. -  10. 4.",
              "26. 4. -  4. 5.",
              "24. 5. -  29. 5.",
              "31. 5. - 5. 6.",
              "13. 9. -  21. 9.",
              "4. 10. - 12.10.",
              "17. 10. - 19. 10.",
              "25. 10. -  2. 11.",
              "15. 11. -  23. 11.",
              "29. 11. -  7. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg","img/mis/fr1.svg","img/mis/fb1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/js1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
  ],
    "citys" : ["Poproč",
               "Víťaz",
               "Brezno - Mezorníkovo",
               "Sabinov",
               "Prešov",
               "Švošov",
               "Myjava",
               "Levoča",
               "Nitra - Chrenová",
               "Spišské Podhradie",
               "Poproč",
               "Nedašov - Brumov",
               "Šúrovce",
               "Snina"],
  },
{
    "status": ["Misie",
               "Obnova",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Obnova",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2004.svg",
    "year" : 2004,
    "diecezis": ["Nitrianska diecéza",
                 "Rožňavská diecéza",
                 "Spišská diecéza",
                 "Temešvárska diecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Košická arcidiecéza",
                 "Nitrianska diecéza"
  ],
    "admin":["Peter Hluzák",
             "Dušan Mesík",
             "Anton Mišek",
             "",
             "Ján Stašák",
             "Peter Heske",
             "Jaroslav Naščák",
             "Peter Majerník",
             "Štefan Kojš",
             "Pavol Marton",
             "Ján Švec Bilý",
             "Štefan Herényi",
             "Peter Gombita",
             "Karol František Pati"
  ],
    "date" : ["10. 1. - 18. 1.",
              "31. 1. -  5. 2.",
              "28. 2. -  7. 3.",
              "13. 3. -  28. 3.",
              "17. 4. -  25. 4.",
              "1. 5. -  9. 5.",
              "22. 5. -  27. 5.",
              "5. 6. - 13. 6.",
              "4. 9. -  12. 9.",
              "25. 9. - 3.10.",
              "9. 10 - 17. 10.",
              "23. 10. -  31. 10.",
              "13. 11. -  21. 11.",
              "11. 12. -  19. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/ms1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg","img/mis/ms1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/rb1.svg","img/mis/rd1.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg"]
  ],
    "citys" : ["Predmier",
               "Brezno - Mezorníkovo",
               "Spišská Nová Ves",
               "Butin a Nová Huta- Rumunsko",
               "Ždiar",
               "Sedlice",
               "Sabinov",
               "Košická Polianka",
               "Veličná",
               "Bardejov",
               "Stropkov",
               "Bratislava - Blumentál",
               "Svidník",
               "Vráble"],
  },
{
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Obnova",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2005.svg",
    "year" : 2005,
    "diecezis": ["Spišská diecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Nitrianska diecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Banskobystrická diecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Rožňavská diecéza",
                 "Nitrianska diecéza"

  ],
    "admin":["Marcel Matava",
             "Juraj Riško",
             "Miloš Ubáľ",
             "Dominik Lejman",
             "Pavol Marton",
             "Jakub Grich",
             "Peter Vychlopeň",
             "Ján Marhefka",
             "František Šandor",
             "Imrich Anderko",
             "Pavol Bodnár",
             "Milan Krajčo"

  ],
    "date" : ["15. 1. - 23. 1.",
              "29. 1. -  6. 2.",
              "5. 3. -  13. 3.",
              "9. 4. -  17. 4.",
              "7. 5. -  12. 5.",
              "28. 5. -  5. 6.",
              "3. 9. -  11. 9.",
              "24. 9. - 2. 10.",
              "8. 10. -  16. 10.",
              "22. 10. - 30.10.",
              "12. 11. -  20. 11.",
              "10. 12. -  18. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg","img/mis/ms1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/ps2.svg","img/mis/vh1.svg","img/mis/ms1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg","img/mis/ms1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/rb1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg","img/mis/ms1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/ms1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/ph1.svg"],

  ],
    "citys" : ["Spišské Hanušovce",
               "Hanušovce nad Topľou",
               "Žaškov",
               "Topoľčany - sídlisko",
               "Bardejov",
               "Kežmarok",
               "Kľak",
               "Trdošín",
               "Košice - Dóm",
               "Terňa",
               "Závadka nad Hronom",
               "Drietoma"],
  },
{
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2006.svg",
    "year" : 2006,
    "diecezis": ["Spišská diecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Spišská diecéza",
                 "Banskobystrická diecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Nitrianska diecéza",
                 "Košická arcidiecéza",
                 "Nitrianska diecéza"

  ],
    "admin":["Peter Kvašňák",
             "Zdeno Sitka",
             "Štefan Koma",
             "Ján Flajžík",
             "Ján Dorotčin",
             "Amantius Akimjak",
             "Imrich Vaško",
             "pátri piaristi",
             "František Romaňák",
             "Marián Ďurčan"
  ],
    "date" : ["15. 1. - 23. 1.",
              "11. 2. -  19. 2.",
              "25. 3. -  2. 4.",
              "22. 4. -  30. 4.",
              "20. 5. -  28. 5.",
              "3. 6. -  11. 6. ",
              "25. 9. -  1. 10.",
              "14. 10. - 22. 10.",
              "18. 11. -  26. 11.",
              "9. 12. - 17. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg","img/mis/jj1.svg","img/mis/ps2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/rb1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/rb1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/mm2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg","img/mis/fb1.svg","img/mis/ps1.svg","img/mis/bl1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/ph1.svg"]

  ],
    "citys" : ["Lúčky",
               "Pezinok",
               "Liesek",
               "Jastrabá",
               "Trenčianské Teplice",
               "Klčov",
               "Ružomberok KU",
               "Trenčín",
               "Gaboltov",
               "Domaniža"],
  },
{
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Obnova",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2007.svg",
    "year" : 2007,
    "diecezis": ["Spišská diecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Košická arcidiecéza",
                 "Bratislavsko-trnavská arcidiecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Bratislavsko-trnavska arcidiecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Nitrianska arcidiecéza",
                 "Spišská diecéza"
  ],
    "admin":["Ján Farkašovský",
             "Vladimír Študent",
             "Dušan Nemec",
             "Jozef Bohunický",
             "Ján Štefanec",
             "Peter Bolibruch",
             "Vladimír Baxa",
             "Juraj Rendeš",
             "",
             "Miroslav Lysičan",
             "Štefan Saloha",

  ],
    "date" : ["3. 2. - 11. 2.",
              "17. 3. -  25. 3.",
              "21. 4. -  29. 4.",
              "12. 5. -  20. 5. ",
              "9. 6. -  17. 6.",
              "1. 9. -  9. 9.",
              "22. 9. -  30. 9.",
              "20. 10. - 28. 10.",
              "5. 11. - 8. 11.",
              "10. 11. -  18. 11.",
              "1. 12. - 9. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mh1.svg","img/mis/vh1.svg","img/mis/ms1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/ph1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/pg1.svg","img/mis/ja1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/jj1.svg","img/mis/mm2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/rd1.svg","img/mis/ps2.svg"],
                  ["img/mis/mz1.svg","img/mis/rb1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/ms1.svg"],
                  ["img/mis/mz1.svg","img/mis/rb1.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg"]

  ],
    "citys" : ["Nižná",
               "Trnava - Kopánka",
               "Humenné",
               "Piešťany",
               "Nitra - Kalvária",
               "Bobrovec",
               "Bratislava - Miletičova",
               "Prešov",
               "KÚ Ružomberok",
               "Omšenie",
               "Kňažia"],
  },
  {
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2008.svg",
    "year" : 2008,
    "diecezis": ["Nitrianska diecéza",
                 "Košická arcidiecéza",
                 "Banskobystrická diecéza",
                 "Spišská diecéza",
                 "Banskobystrická diecéza",
                 "Košická arcidiecéza",
                 "Vilškaviská diecéza",
                 "Bratislavská arcidiecéza",
                 "Banskobystrická diecéza",
                 "Žilinská diecéza",
                 "Spišská diecéza"
],
    "admin":["Roman Galas",
             "Jozef Smatanka",
             "Miroslav Baláž",
             "Vincent Dzurňák",
             "Marek Kosorín",
             "Tibor Zavatský",
             "Rimantas Norvila",
             "Pavol Flajžík",
             "Pavol Michalovič",
             "Marián Bundzel",
             "Jozef Golvoň"],
    "date" : ["13. 1. - 21. 1.",
              "27. 1. -  3. 2.",
              "1. 3. -  9. 3.",
              "29. 3. -  6. 4.",
              "24. 5. -  1. 6.",
              "7. 6. -  15. 6.",
              "8. 9. -  15. 9.",
              "20. 9. - 28. 9.",
              "11. 10. -  19. 10.",
              "8. 11. - 16. 11.",
              "6. 12. - 14. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/rb1.svg","img/mis/vh1.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/rr1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"]],
    "citys" : ["Dolný Ohaj",
               "Kendice",
               "Banská Bystrica - Fončorda",
               "Lesnica",
               "Veľký Krtíš",
               "Vranov - Juh",
               "Litva - Marijanpol",
               "Jablonica",
               "Prievidza",
               "Žilina - Hliny",
               "Hladovka"],
  },
  {
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Obnova",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2009.svg",
    "year" : 2009,
    "diecezis": ["Spišská diecéza",
                 "Spišská diecéza",
                 "Olomoucká arcidiecéza",
                 "Bratislavská arcidiecéza",
                 "Banskobystrická diecéza",
                 "Oradea diecéza",
                 "Spišská diecéza",
                 "Bratislavská arcidiecéza",
                 "Košická arcidiecéza",
                 "Nitrianska diecéza"
  ],
    "admin":["Ján Hudák",
             "Igor Dlugosek",
             "Richard Wojciechowski",
             "Jozef Duc",
             "Marek Kosorín",
             "Ján Mlynarčík",
             "František Piosek",
             "Michal Pokopec",
             "Jozef Gnip",
             "Jaroslav Ondráš"
  ],
    "date" : ["10. 1. - 18. 1.",
              "31. 1. -  8. 2.",
              "21. 3. -  29. 3.",
              "9. 5. -  17. 5.",
              "23. 5. -  28. 5. ",
              "7. 6. -  14. 6.",
              "6. 6. -  14. 6.",
              "19. 9. - 27. 9.",
              "3. 10. -  11. 10.",
              "12. 12. - 20. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/ps2.svg"],
                  ["img/mis/mz1.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mh1.svg"],
                  ["img/mis/vh1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/ph1.svg"],
  ],
    "citys" : ["Spišská Stará Ves",
               "Komjatná",
               "Nedašov",
               "Bratislava - Petržalka",
               "Veľký Krtíš",
               "Rumunsko - Oradea",
               "Breza",
               "Šenkvice",
               "Trebišov",
               "Horná Súča"],
  },
{
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2010.svg",
    "year" : 2010,
    "diecezis": ["Bratislavská arcidiecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Bratislavská arcidiecéza",
                 "Spišská diecéza",
                 "Bratislavská arcidiecéza"
  ],
    "admin":["Peter Slepčan",
             "Michal Tkáč",
             "Allan Tomáš",
             "Ján Urban",
             "Jozef Barila",
             "Vladimír Klein",
             "Lucián Bogucki",
             "František Kohút",
             "Alfonz Sabo"

  ],
    "date" : ["16. 1. - 24. 1.",
              "20. 2. - 28. 2.",
              "13. 3. - 21. 3.",
              "24. 4. - 2. 5.",
              "5. 6. - 13. 6.",
              "18. 9. - 26. 9.",
              "16. 10. - 24. 10.",
              "6. 11. - 14. 11.",
              "27. 11. - 5. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/ps1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/ps1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
  ],
    "citys" : ["Vajnory",
               "Rozhanovce",
               "Snina - mesto",
               "Košice - Furča",
               "Vyšné Ružbachy",
               "Novoť",
               "Bratislava - Karlová Ves",
               "Poprad - Veľká",
               "Vištuk"],
  },
  {
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2011.svg",
    "year" : 2011,
    "diecezis": ["Žilinská diecéza",
                 "Žilinská diecéza",
                 "Bratislavská arcidiecéza",
                 "Žilinská diecéza",
                 "Spišská diecéza",
                 "Timisoara diecéza",
                 "Košická diecéza",
                 "Žilinská diecéza",
                 "Spišská diecéza",
                 "Bratislavská arcidiecéza"],
    "admin":["Štefan Wallner",
             "Radoslav Gazdík",
             "František Moško",
             "Róbert Krajčík",
             "Miroslav Slotka",
             "Demeter Salman",
             "Peter Bučko",
             "Peter Holbička",
             "Andrej Barnáš",
             "Lukáš Šlosár"],
    "date" : ["29. 1. - 6. 2.",
              "19. 2. - 27. 2.",
              "19. 3. - 27. 3.",
              "2. 4. - 10. 4. ",
              "28. 5. - 5. 6.",
              "16. 8. - 21. 8.",
              "24. 9. - 2. 10.",
              "15. 10. - 23. 10.",
              "12. 11. - 20. 11.",
              "10. 12. - 18. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/sv1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/vh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/jn1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/ps2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg","img/mis/mm2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/vh1.svg"]],
    "citys" : ["Nová Dubnica",
               "Veľké Rovné",
               "Grinava",
               "Martin - Sever",
               "Hniezdne",
               "Nadlac, Rumunsko",
               "Zborov",
               "Žilina - mesto",
               "Mútne",
               "Gbely"],
  },
  {
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2012.svg",
    "year" : 2012,
    "diecezis": ["Spišská diecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Žilinská diecéza",
                 "Spišská diecéza",
                 "Banskobystrická diecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Bratislavská arcidiecéza",
                 "Spišská diecéza"],
    "admin":["Peter Petrek",
             "Miroslav Kyšeľa",
             "Gabriel Brendza",
             "Stanislav Pavúk",
             "Viktor Kuciak",
             "Jaroslav Chovanec",
             "Michal Krovina",
             "",
             "Marek Kreheľ",
             "Marián Vojtko",
             "Štefan Vitko"],
    "date" : ["14. 1. - 22. 1.",
              "11. 2. - 19. 2.",
              "17. 3. - 25. 3.",
              "21. 4. - 29. 4.",
              "12. 5. - 20. 5.",
              "9. 6. - 17. 6.",
              "15. 9. - 23. 9.",
              "1. 10. - 7. 10.",
              "20. 10. - 28. 10.",
              "10. 11. - 18. 11.",
              "1. 12. - 9. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/rr1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/mm2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/fb1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/vh1.svg","img/mis/pg1.svg","img/mis/ps2.svg",],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/vh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/mm2.svg","img/mis/rd1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg"]],
    "citys" : ["Spišská Belá",
               "Široké",
               "Selce",
               "Ohradzany",
               "Čadca - Kýčerka",
               "Trstená",
               "Zvolen - Západ",
               "Ružomberok KU",
               "Prešov - Sekčov",
               "Borský Svätý Jur",
               "Svit"],
  },
  {
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Obnova",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2013.svg",
    "year" : 2013,
    "diecezis": ["Košická arcidiecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Rožňavská diecéza",
                 "Košická diecéza",
                 "Banskobystrická diecéza",
                 "Spišská diecéza",
                 "diecézy New York a Paterson",
                 "Spišská diecéza",
                 "Prešovská eparchia",
                 "Banskobystrická diecéza"
               ],
    "admin":["Marián Babjarčík",
             "Ján Budzák",
             "Ladislav Cichý",
             "Jaroslav Humenný",
             "Pavol Bodnár",
             "Michal Marčák",
             "Gabriel Brendza",
             "Igor Jendruch",
             "Š. Chanas a M. Kertys",
             "Pavol Jurčišin",
             "Marián Pacák",
             "Andrej Karcagi"],
    "date" : ["12. 1. - 20. 1.",
              "2. 2. - 10. 2.",
              "9. 3. - 17. 3.",
              "20. 4. - 28. 4.",
              "25. 5. - 2. 6.",
              "8. 6. - 16. 6.",
              "1. 7. - 4. 7.",
              "31. 8. - 8. 9.",
              "19. 9. - 7. 10.",
              "12. 10. - 20. 10.",
              "3. 11. - 10. 11.",
              "23. 11. - 1. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/vh1.svg","img/mis/rr1.svg","img/mis/jn1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm1.svg","img/mis/mh1.svg","img/mis/rr1.svg","img/mis/jn1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/rr1.svg","img/mis/jn1.svg"],
                  ["img/mis/mz1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/rr1.svg","img/mis/jn1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"]
                ],
    "citys" : ["Ľubotín",
               "Liptovské Sliače",
               "Sabinov",
               "Rabčice",
               "Revúca",
               "Lipany",
               "Selce",
               "Nižné Ružbachy",
               "New York a Clifton (USA)",
               "Zubrohlava",
               "Stará Ľubovňa",
               "Hontiarské Trsťany"],
  },
  {
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2014.svg",
    "year" : 2014,
    "diecezis": ["Spišská diecéza",
                 "Nitrianska diecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Karaganda diecéza",
                 "Oradea diecéza",
                 "Spišská diecéza",
                 "Košická diecéza",
                 "Košická diecéza",
                 "Košická diecéza",
                 "Spišská diecéza"
  ],
    "admin":["Rudolf Pitoňák",
             "Cyril Lieskovský",
             "Martin Tondra",
             "Ján Švec-Bilý",
             "Janusz Potom",
             "Augustín Albert",
             "Róbert Tokár",
             "Pavol Marton",
             "Peter Kyšeľ",
             "Peter Sepeši",
             "Matúš Perignáth"
  ],
    "date" : ["18. 1. - 26. 1.",
              "15. 2. - 23. 2.",
              "30. 3. - 6. 4.",
              "10. 5. - 18. 5.",
              "14. 6. - 22. 6.",
              "29. 6. - 5. 7.",
              "30. 8. - 7. 9.",
              "20. 9. - 28. 9.",
              "18. 10. - 26. 10.",
              "15. 11. - 23. 11.",
              "6. 12. - 14. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg","img/mis/jn1.svg"],
                  ["img/mis/mz1.svg","img/mis/mm2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/jj2.svg"],
                  ["img/mis/mz1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/rr1.svg","img/mis/jn1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
  ],
    "citys" : ["Letanovce",
               "Palárikovo",
               "Oravská Lesná",
               "Stropkov",
               "Karaganda (Kazachtan)",
               "Nová Huta (Rumunsko)",
               "Vysoké Tatry",
               "Bardejov",
               "Šarišské Michaľany",
               "Kamenica nad Cirochou",
               "Rudňany"],
  },
  {
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2015.svg",
    "year" : 2015,
    "diecezis": ["Spišská diecéza",
                 "Ostravsko-opatská diecéza",
                 "Banskobystrická diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Pražská arcidiecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Nitrianska diecéza",
                 "Bratislavská arcidiecéza",
                 "Spišská diecéza"],
    "admin":["Miloš Labaš",
             "Anton Verbovský",
             "Michal Repiský",
             "Blažej Dibdiak",
             "Ján Marťak",
             "",
             "Marcel Matava",
             "František Mariňák",
             "Stanislav Caránek",
             "Pavol Poša",
             "Peter Lovas"],
    "date" : ["24. 1. - 1. 2.",
              "7. 2. - 15. 2.",
              "14. 3. - 22. 3.",
              "18. 4. - 26. 4.",
              "9. 5. - 17. 5.",
              "30. 5. - 7. 6.",
              "20. 6. - 28. 6.",
              "19. 9. - 27. 9.",
              "17. 10. - 25. 10.",
              "14. 11. - 22. 11.",
              "5. 12. - 13. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/ph1.svg"],
                  ["img/mis/mz1.svg","img/mis/mm2.svg","img/mis/ps2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/rr1.svg","img/mis/rd1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/vh1.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/vh1.svg","img/mis/jj2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"]],
    "citys" : ["Stankovany",
               "Frýdek (Cz)",
               "Detvianská Huta",
               "Námestovo",
               "Spišská Kapitula",
               "Praha (Cz)",
               "Liptovský Hradok",
               "Humenné - mesto",
               "Žitavany",
               "Svätý Jur",
               "Švošov"],
  },
  {
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Obnova",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2016.svg",
    "year" : 2016,
    "diecezis": ["Košická arcidiecéza",
                 "Spišská diecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Bratislavská arcidiecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Banskobystrická diecéza",
                 "Košická arcidiecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza"],
    "admin":["Michal Tkáč",
             "Karol Karaš",
             "Jozef Smatanka",
             "Peter Marčák",
             "Peter Slepčan",
             "Marek Kunder",
             "Peter Kvašňák",
             "Andrej Borsík",
             "Ľubomír Sabol",
             "František Mariňák",
             "Marek Pristaš",
             "Jozef Benko"],
    "date" : ["23. 1. - 31. 1.",
              "20. 2. - 8. 2.",
              "5. 3. - 13. 3.",
              "16. 4. - 24. 4.",
              "23. 5. - 29. 5.",
              "11. 6. - 19. 6.",
              "3. 9. - 11. 9.",
              "24. 9. - 2. 10.",
              "15. 10. - 23. 10.",
              "28. 10. - 1. 11.",
              "13. 11. - 20. 11.",
              "3. 12. - 11. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/jn1.svg","img/mis/jz1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/vh1.svg","img/mis/rd1.svg","img/mis/jj2.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/rr1.svg","img/mis/jn1.svg","img/mis/ab1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg","img/mis/ps2.svg","img/mis/jm1.svg"],
                  ["img/mis/mz1.svg","img/mis/rd1.svg","img/mis/ja1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"]],
    "citys" : ["Šaca",
               "Valaská Dubová",
               "Plaveč",
               "Svidník",
               "Bratislava - katedrála",
               "Čeremné",
               "Lúčky",
               "Poprad",
               "Detva",
               "Humenné",
               "Budkovce",
               "Veľká Lomnica"],
  },
  {
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2017.svg",
    "year" : 2017,
    "diecezis": ["Spišská diecéza",
                 "Trnavská diecéza",
                 "Košická arcidiecéza",
                 "Žilinská diecéza",
                 "Košická diecéza",
                 "Košická diecéza",
                 "Spišská diecéza",
                 "Bratislavská arcidiecéza",
                 "Žilinská diecéza"],
    "admin":["Jozef Šimurdiak",
             "Blažej Čaputa",
             "Peter Novák",
             "Pavol Pečko",
             "Ivan Jakubík",
             "Marek Hnát",
             "Vladimír Bolibruch",
             "Chryzostom Kryštof",
             "Marián Ďurčan"],
    "date" : ["21. 1. - 29. 1.",
              "18. 2. - 26. 2.",
              "25. 3. - 2. 4.",
              "22. 4. - 30. 4.",
              "20. 5. - 28. 5.",
              "10. 6. - 18. 6.",
              "9. 9. - 17. 9. ",
              "6. 10. - 13. 10.",
              "25. 11. - 3. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg","img/mis/ab1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/mm2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg","img/mis/jn1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg","img/mis/jn1.svg"],
                  ["img/mis/mz1.svg","img/mis/mm2.svg","img/mis/rr1.svg","img/mis/jn1.svg"],
                  ["img/mis/mz1.svg","img/mis/mm2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/vh1.svg","img/mis/rd1.svg","img/mis/ja1.svg","img/mis/jj2.svg","img/mis/pg1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg","img/mis/ab1.svg"]],
    "citys" : ["Spišské Vlachy",
               "Nové Mesto nad Váhom",
               "Košice - KVP",
               "Sučany",
               "Raslavice",
               "Víťaz",
               "Zuberec",
               "Bratislava - Kalvária",
               "Konská"],
  },
  {
    "status": ["Misie",
               "Misie",
               "Misie",
               "Misie",
               "Obnova",
               "Misie",
               "Obnova",
               "Obnova",
               "Misie",
               "Misie",
               "Misie"],
    "plan" : "Plán misií",
    "show" : false,
    "mapa" : "Mapa misií",
    "mapa_link":"img/svg/misie2018.svg",
    "year" : 2018,
    "diecezis": ["Spišská diecéza",
                 "Košická arcidiecéza",
                 "Spišská diecéza",
                 "Spišská diecéza",
                 "Spišská diecéza"
  ],
    "admin":["Ondrej Želonka",
             "Bartolomej Salanci",
             "Daniel Šalát"
  ],
    "date" : ["20. 1. - 28. 1.",
              "17. 2. - 25. 2.",
              "10. 3. - 18. 3.",
              "14. 4. - 22. 4.",
              "9. 5. - 13. 5.",
              "20. 5. - 27. 5.",
              "6. 6. - 10. 6.",
              "5. 9. - 8. 9.",
              "22. 9. - 29. 9.",
              "21. 10. - 28. 10.",
              "24. 11. - 2. 12."],
    "missionars":[["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/rr1.svg","img/mis/ab1.svg"],
                  ["img/mis/mz1.svg","img/mis/mz2.svg","img/mis/ab1.svg"],
                  [],
                  ["img/mis/mz1.svg","img/mis/mz2.svg"],

  ],
    "citys" : ["Spišské Hanušovce",
               "Veľký Šariš",
               "Spišský Štiavnik",
               "Nižná",
               "Brezovica",
               "Hriňová",
               "Zuberec",
               "Nové Mesto nad Váhom",
               "Zlaté Moravce",
               "Hôrka pri Porade",
               "Slovenská Kajňa"],
  }
]

const app = new Vue({
  el: '#app',
  data: {
    show: false,
    missions: missions,
    showLi: false,
  }
});

$(document).scroll(function() {
  var y = $(this).scrollTop();
  if (y > 200) {
    $('.up').fadeIn();
  } else {
    $('.up').fadeOut();
  }
});

$("li>a").on("click", function() {
  var element = $(this).attr("href");
  var dist = $(element).offset().top;
  $("html, body").animate({"scrollTop": dist}, 2000);
  return false;
});
$(".up").on("click", function() {
  $("html, body").animate({"scrollTop": 0}, 2000);
  return false;
});

$("ul").on("click", function(){
    $(".menu").css("display", "none");
    $(this).find(".menu").css("display", "block");
  });
