let dk = [{
  year: 1992,
  goalie:[{
    name: "Мартінкенас",
    form: "fas fa-tshirt",
    nation: "./img/flags/lt.svg",
    Ycard:"0",
    Rcard: "0",
    goals: -8,
    game: 11,
    minuts: "1020 m",
    },
    {
    name: "Кутепов",
    form: "fas fa-tshirt",
    nation: "./img/flags/ua.svg",
    Ycard:"0",
    Rcard: "0",
    goals: -9,
    game: 12,
    minuts: "1080 m",
  }],
  defender:[{
        name: "Шматоваленко",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 0,
        Rcard: 0,
        goals: 0,
        game: 11,
        minuts: "974 m",
        },
        {
          name: "Квіткаускас",
          form: "fas fa-tshirt blue",
          nation: "./img/flags/lt.svg",
          Ycard: 0,
          Rcard: 0,
          goals: 0,
          game: 7,
          minuts: "437 m",
          },
          {
            name: "Безсмертний",
            form: "fas fa-tshirt blue",
            nation: "./img/flags/ua.svg",
            Ycard: 1,
            Rcard: 0,
            goals: 0,
            game: 16,
            minuts: "1400 m",
            },
            {
              name: "Цвейба",
              form: "fas fa-tshirt blue",
              nation: "./img/flags/ru.svg",
              Ycard: 0,
              Rcard: 0,
              goals: 1,
              game: 12,
              minuts: " 1003 m",
              },
            {
              name: "Заєць",
              form: "fas fa-tshirt blue",
              nation: "./img/flags/ua.svg",
              Ycard: 0,
              Rcard: 0,
              goals: 1,
              game: 18,
              minuts: "1560 m",
              },
          {
            name: "Лужний",
            form: "fas fa-tshirt blue",
            nation: "./img/flags/ua.svg",
            Ycard: 2,
            Rcard: 0,
            goals: 2,
            game: 16,
            minuts: "1353 m",
            },
          {
            name: "Анненков",
            form: "fas fa-tshirt blue",
            nation: "./img/flags/ua.svg",
            Ycard: 0,
            Rcard: 0,
            goals: 1,
            game: 20,
            minuts: "1830 m",
            },
        {
          name: "Сукіасян",
          form: "fas fa-tshirt blue",
          nation: "./img/flags/am.svg",
          Ycard: 0,
          Rcard: 0,
          goals: 2,
          game: 8,
          minuts: "630 m",
          },
        {
          name: "Алексаненков",
          form: "fas fa-tshirt blue",
          nation: "./img/flags/ua.svg",
          Ycard: 0,
          Rcard: 0,
          goals: 0,
          game: 3,
          minuts: "270 m",
          }],
  midfield:[
      {
        name: "Волотьок",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 0,
        Rcard: 0,
        goals: 2,
        game: 14,
        minuts: "940 m",
        },
      {
        name: "Ковалець",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 0,
        Rcard: 0,
        goals: 1,
        game: 14,
        minuts: "870 m",
        },
      {
        name: "Шаран",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 0,
        Rcard: 0,
        goals: 2,
        game: 23,
        minuts: "1582 m",
        },
      {
        name: "Беца",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 0,
        Rcard: 0,
        goals: 1,
        game: 17,
        minuts: "1055 m",
        },
      {
        name: "Яковенко",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 1,
        Rcard: 0,
        goals: 2,
        game: 16,
        minuts: "1232 m",
        },
      {
        name: "Мороз",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 0,
        Rcard: 0,
        goals: 0,
        game: 23,
        minuts: "1822 m",
        }],
  forward:[{
      name: "Матвеєв",
      form: "fas fa-tshirt blue",
      nation: "./img/flags/ua.svg",
      Ycard: 0,
      Rcard: 0,
      goals: 1,
      game: 13,
      minuts: "788 m",
    },
    {
      name: "Єсипов",
      form: "fas fa-tshirt blue",
      nation: "./img/flags/ru.svg",
      Ycard: 0,
      Rcard: 0,
      goals: 1,
      game: 7,
      minuts: "474 m",
      },
    {
      name: "Леоненко",
      form: "fas fa-tshirt blue",
      nation: "./img/flags/ua.svg",
      Ycard: 0,
      Rcard: 0,
      goals: 3,
      game: 6,
      minuts: "448 m",
      },
    {
      name: "Саленко",
      form: "fas fa-tshirt blue",
      nation: "./img/flags/ru.svg",
      Ycard: 1,
      Rcard: 0,
      goals: 8,
      game: 20,
      minuts: "1625 m",
      },
    {
      name: "Грицина",
      form: "fas fa-tshirt blue",
      nation: "./img/flags/ua.svg",
      Ycard: 0,
      Rcard: 0,
      goals: 7,
      game: 17,
      minuts: "1121 m",
      }]
},
{
  year: "1992/1993",
  goalie:[{
    name: "Мартінкенас",
    form: "fas fa-tshirt",
    nation: "./img/flags/lt.svg",
    Ycard: 0,
    Rcard: 0,
    goals: "???",
    game: 19,
    minuts: "??? m",
    },
    {
    name: "Кутепов",
    form: "fas fa-tshirt",
    nation: "./img/flags/ua.svg",
    Ycard: 0,
    Rcard: 0,
    goals: "???",
    game: 12,
    minuts: "??? m",
  }],
  defender:[{
        name: "Шматоваленко",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 1,
        Rcard: 0,
        goals: 1,
        game: 22,
        minuts: "??? m",
        },
        {
          name: "Дем'яненко",
          form: "fas fa-tshirt blue",
          nation: "./img/flags/lt.svg",
          Ycard: 0,
          Rcard: 0,
          goals: 1,
          game: 14,
          minuts: "??? m",
          },
          {
            name: "Безсмертний",
            form: "fas fa-tshirt blue",
            nation: "./img/flags/ua.svg",
            Ycard: 0,
            Rcard: 0,
            goals: 0,
            game: 9,
            minuts: "??? m",
            },
            {
              name: "Цвейба",
              form: "fas fa-tshirt blue",
              nation: "./img/flags/ru.svg",
              Ycard: 0,
              Rcard: 0,
              goals: 0,
              game: 12,
              minuts: "??? m",
              },
            {
              name: "Заєць",
              form: "fas fa-tshirt blue",
              nation: "./img/flags/ua.svg",
              Ycard: 1,
              Rcard: 0,
              goals: 1,
              game: 11,
              minuts: "??? m",
              },
          {
            name: "Лужний",
            form: "fas fa-tshirt blue",
            nation: "./img/flags/ua.svg",
            Ycard: 2,
            Rcard: 0,
            goals: 3,
            game: 26,
            minuts: "??? m",
            },
          {
            name: "Анненков",
            form: "fas fa-tshirt blue",
            nation: "./img/flags/ua.svg",
            Ycard: 1,
            Rcard: 0,
            goals: 2,
            game: 21,
            minuts: "??? m",
            },
        {
          name: "Сукіасян",
          form: "fas fa-tshirt blue",
          nation: "./img/flags/am.svg",
          Ycard: 0,
          Rcard: 0,
          goals: 0,
          game: 3,
          minuts: "??? m",
          },
        {
          name: "Алексаненков",
          form: "fas fa-tshirt blue",
          nation: "./img/flags/ua.svg",
          Ycard: 1,
          Rcard: 0,
          goals: 0,
          game: 8,
          minuts: "??? m",
        },
      {
        name: "Пономаренко",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 0,
        Rcard: 0,
        goals: 0,
        game: 15,
        minuts: "??? m",
        },
      {
        name: "Зуєнко",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 0,
        Rcard: 0,
        goals: 0,
        game: 8,
        minuts: "??? m",
        },
      {
        name: "Панкратьєв",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/lt.svg",
        Ycard: 3,
        Rcard: 0,
        goals: 2,
        game: 9,
        minuts: "??? m",
        }],
  midfield:[{
          name: "Топчієв",
          form: "fas fa-tshirt blue",
          nation: "./img/flags/ua.svg",
          Ycard: 1,
          Rcard: 0,
          goals: 7,
          game: 14,
          minuts: "??? m",
              },
            {
              name: "Ковалець",
              form: "fas fa-tshirt blue",
              nation: "./img/flags/ua.svg",
              Ycard: 1,
              Rcard: 0,
              goals: 1,
              game: 27,
              minuts: "??? m",
              },
            {
              name: "Шаран",
              form: "fas fa-tshirt blue",
              nation: "./img/flags/ua.svg",
              Ycard: 1,
              Rcard: 0,
              goals: 1,
              game: 16,
              minuts: "??? m",
              },
            {
              name: "Беца",
              form: "fas fa-tshirt blue",
              nation: "./img/flags/ua.svg",
              Ycard: 0,
              Rcard: 0,
              goals: 0,
              game: 8,
              minuts: "??? m",
              },
            {
              name: "Яковенко",
              form: "fas fa-tshirt blue",
              nation: "./img/flags/ua.svg",
              Ycard: 1,
              Rcard: 0,
              goals: 1,
              game: 9,
              minuts: "??? m",
              },
            {
              name: "Мороз",
              form: "fas fa-tshirt blue",
              nation: "./img/flags/ua.svg",
              Ycard: 0,
              Rcard: 0,
              goals: 0,
              game: 2,
              minuts: " m",
            },
{
  name: "Мізін",
  form: "fas fa-tshirt blue",
  nation: "./img/flags/ua.svg",
  Ycard: 0,
  Rcard: 0,
  goals: 5,
  game: 16,
  minuts: "??? m",
  },
  {
    name: "Ребров",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
    Ycard: 0,
    Rcard: 0,
    goals: 5,
    game: 23,
    minuts: "??? m",
    },
  {
    name: "Волотек",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
    Ycard: 0,
    Rcard: 0,
    goals: 0,
    game: 2,
    minuts: "??? m",
    },
  {
    name: "Хруслов",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
    Ycard: 1,
    Rcard: 0,
    goals: 1,
    game: 11,
    minuts: "??? m",
    },
  {
    name: "Зав'ялов",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/tm.svg",
    Ycard: 0,
    Rcard: 0,
    goals: 1,
    game: 5,
    minuts: "??? m",
    },
  {
    name: "Белкін",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
    Ycard: 0,
    Rcard: 0,
    goals: 0,
    game: 2,
    minuts: "??? m",
    }],
  forward:[{
        name: "Мінтенко",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 0,
        Rcard: 0,
        goals: 1,
        game: 10,
        minuts: "??? m",
      },
      {
        name: "Шкапенко",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ru.svg",
        Ycard: 0,
        Rcard: 0,
        goals: 8,
        game: 27,
        minuts: "??? m",
        },
      {
        name: "Леоненко",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 2,
        Rcard: 0,
        goals: 16,
        game: 27,
        minuts: "??? m",
        },
      {
        name: "Грицина",
        form: "fas fa-tshirt blue",
        nation: "./img/flags/ua.svg",
        Ycard: 1,
        Rcard: 0,
        goals: 2,
        game: 20,
        minuts: "??? m",
        }]

},
{ year: "1993/1994",
goalie:[{
    name: "Ковтун",
    form: "fas fa-tshirt",
    nation: "./img/flags/ua.svg",
    Ycard: 1,
    Rcard: 0,
    goals: -7,
    game: 15,
    minuts: "1350 m"
  },
  {
    name: "Шовковський",
    number: 0,
    form: "fas fa-tshirt",
    nation: "./img/flags/ua.svg",
    Ycard: 0,
    Rcard: 0,
    goals: -6,
    game: 9,
    minuts: "810 m",
  },
  {
    name: "Кутепов",
    form: "fas fa-tshirt",
    nation: "./img/flags/ua.svg",
    number: 0,
    Ycard: 1,
    Rcard: 0,
    goals: -15,
    game: 16,
    minuts: "1440 m",
    }
],
defender:[
  {
    name: "Ващук",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
    Ycard: 0,
    Rcard: 0,
    goals: 1,
    game: 28,
    minuts: "2067 m",
  },
  {
    name: "Безсмертний",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
    Ycard: 3,
    Rcard: 0,
    goals: 0,
    game: 12,
    minuts: "827 m",
  },
  {
    name: "Лужний",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
    Ycard: 1,
    Rcard: 0,
    goals: 1,
    game: 40,
    minuts: "3600 m",
  },
  {
    name: "Анненков",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
    Ycard: 2,
    Rcard: 0,
    goals: 1,
    game: 15,
    minuts: "1145 m",
  },
  {
    name: "Хомін",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/tm.svg",
    Ycard: 3,
    Rcard: 0,
    goals: 1,
    game: 19,
    minuts: "1658 m",
  },
  {
    name: "Федоров",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
    Ycard: 0,
    Rcard: 0,
    goals: 0,
    game: 1,
    minuts: "84 m",
  },
  {
    name: "Шматоваленко",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
    Ycard: 4,
    Rcard: 0,
    goals: 0,
    game: 33,
    minuts: "2733 m",
  },
  {
    name: "Пономаренко",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
    Ycard: 0,
    Rcard: 0,
    goals: 0,
    game: 25,
    minuts: "2166 m",
  }],
midfield:[
  {
    name: "Топчієв",
    game: 38,
    goals: 6,
    number: 0,
    Ycard: 7,
    Rcard: 0,
    minuts: "3076 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Ковалець",
    game: 31,
    goals: 3,
    number: 0,
    Ycard: 1,
    Rcard: 0,
    minuts: "2354 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Шаран",
    game: 23,
    goals: 4,
    number: 0,
    Ycard: 5,
    Rcard: 0,
    minuts: "1471 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Мізін",
    game: 33,
    goals: 6,
    number: 0,
    Ycard: 5,
    Rcard: 1,
    minuts: "2458 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Ребров",
    game: 13,
    goals: 3,
    number: 0,
    Ycard: 3,
    Rcard: 0,
    minuts: "866 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Хруслов",
    game: 11,
    goals: 1,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    minuts: "689 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Зав'ялов",
    game: 9,
    goals: 2,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    minuts: "307 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/tm.svg",
  },
  {
    name: "Прудіус",
    game: 14,
    goals: 1,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    minuts: "583 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Призетко",
    game: 37,
    goals: 8,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    minuts: "1917 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Деменко",
    game: 0,
    goals: 13,
    number: 0,
    Ycard: 2,
    Rcard: 0,
    minuts: "1055 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ru.svg",
  },
],
forward:[
  {
    name: "Грицина",
    game: 13,
    goals: 0,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    minuts: "748 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Шкапенко",
    game: 37,
    goals: 13,
    number: 0,
    Ycard: 1,
    Rcard: 0,
    minuts: "2943 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Мінтенко",
    game: 14,
    goals: 2,
    number: 0,
    Ycard: 1,
    Rcard: 0,
    minuts: "445 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Джишкаріані",
    game: 13,
    goals: 1,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    minuts: "629 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ge.svg",
  },
  {
    name: "Леоненко",
    game: 26,
    goals: 16,
    number: 0,
    Ycard: 1,
    Rcard: 0,
    minuts: "2080 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  }]
},
{ year: "1994/1995",
goalie:[
  {
    name: "Ковтун",
    game: 5,
    goals: -4,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    minuts: "394 m",
    form: "fas fa-tshirt",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Шовковський",
    game: 27,
    goals: -16,
    number: 0,
    Ycard: 0,
    Rcard: 1,
    minuts: "2396 m",
    form: "fas fa-tshirt",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Воробйов",
    game: 9,
    goals: -8,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    minuts: "810 m",
    form: "fas fa-tshirt",
    nation: "./img/flags/ua.svg",
  }],
defender:[
  {
    name: "Анненков",
    game: 4,
    goals: 0,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    minuts: "180 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Лужний",
    game: 29,
    goals: 4,
    number: 0,
    Ycard: 4,
    Rcard: 0,
    minuts: "2264 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Хомін",
    game: 26,
    goals: 2,
    number: 0,
    Ycard: 3,
    Rcard: 0,
    minuts: "1852 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/tm.svg",
  },
  {
    name: "Ващук",
    game: 37,
    goals: 3,
    number: 0,
    Ycard: 1,
    Rcard: 0,
    minuts: "3174 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Шматоваленко",
    game: 17,
    goals: 0,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    minuts: "1043 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Леженцев",
    game: 26,
    goals: 0,
    number: 0,
    Ycard: 3,
    Rcard: 0,
    minuts: "2049 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Беженар",
    game: 14,
    goals: 1,
    number: 0,
    Ycard: 1,
    Rcard: 0,
    minuts: "1255 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Дмитрулін",
    game: 20,
    goals: 1,
    number: 0,
    Ycard: 1,
    Rcard: 0,
    minuts: "1489 m",
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  }
],
midfield:[
  {
    name: "Косовський",
    game: 29,
    minuts: "2212 m",
    goals: 6,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Мізін",
    game: 26,
    minuts: "1793 m",
    goals: 5,
    number: 0,
    Ycard: 4,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Ребров",
    game: 30,
    minuts: "1488 m",
    goals: 9,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Коновалець",
    game: 21,
    minuts: "1474 m",
    goals: 6,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Максимов",
    game: 15,
    minuts: "1275 m",
    goals: 5,
    number: 0,
    Ycard: 2,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Деменко",
    game: 1,
    minuts: "90 m",
    goals: 0,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ru.svg",
  },
  {
    name: "Прудіус",
    game: 1,
    minuts: "90 m",
    goals: 0,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Шаран",
    game: 13,
    minuts: "583 m",
    goals: 2,
    number: 0,
    Ycard: 3,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Призетко",
    game: 15,
    minuts: "1917 m",
    goals: 1,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Ковалець",
    game: 18,
    minuts: "1055 m",
    goals: 2,
    number: 0,
    Ycard: 2,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Похлєбаєв",
    game: 20,
    minuts: "748 m",
    goals: 3,
    number: 0,
    Ycard: 2,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Калитвинцев",
    game: 18,
    minuts: "1446 m",
    goals: 2,
    number: 0,
    Ycard: 2,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Топчієв",
    game: 2,
    minuts: "180 m",
    goals: 0,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Михайленко",
    game: 27,
    minuts: "2090 m",
    goals: 7,
    number: 0,
    Ycard: 4,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Скаченко",
    game: 17,
    minuts: "1074 m",
    goals: 3,
    number: 0,
    Ycard: 3,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },



],
forward:[
  {
    name: "Шкапенко",
    game: 26,
    minuts: "1263 m",
    goals: 7,
    number: 0,
    Ycard: 1,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Джишкаріані",
    game: 10,
    minuts: "521 m",
    goals: 5,
    number: 0,
    Ycard: 1,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ge.svg",
  },
  {
    name: "Шевченко",
    game: 21,
    minuts: "1117 m",
    goals: 2,
    number: 0,
    Ycard: 1,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Аль-Сюгі",
    game: 1,
    minuts: "37 m",
    goals: 0,
    number: 0,
    Ycard: 0,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },
  {
    name: "Леоненко",
    game: 23,
    minuts: "1753 m",
    goals: 17,
    number: 0,
    Ycard: 2,
    Rcard: 0,
    form: "fas fa-tshirt blue",
    nation: "./img/flags/ua.svg",
  },


]
},
{ year: "1995/1996",},
{ year: "1996/1997",},
{ year: "1997/1998",},
{ year: "1999/2000",},
{ year: "2000/2001",},
{ year: "2001/2002",},
{ year: "2002/2003",},
{ year: "2003/2004",},
{ year: "2004/2005",},
{ year: "2005/2006",},
{ year: "2006/2007",},
{ year: "2007/2008",},
{ year: "2008/2009",},
{ year: "2009/2010",},
{ year: "2010/2011",},
{ year: "2011/2012",},
{ year: "2012/2013",},
{ year: "2013/2014",},
{ year: "2014/2015",},
{ year: "2015/2016",},
{ year: "2016/2017",},
{ year: "2017/2018",},
{ year: "2018/2019",},

]

let app = new Vue({
  el: '.page',
  data: {
    titul:'Гравцi ФК Динамо Київ',
    dk:dk,
  }
})
